/**
 * Node.js email renderer for Cloud Functions.
 *
 * Mirrors src/services/emailRenderer.ts + src/firebase/emailTemplateService.ts
 * so Cloud Functions can use the editable templates stored in Firestore.
 * Falls back to a passed-in default HTML when the template can't be loaded.
 */

const admin = require('firebase-admin');

const COLLECTION = 'emailTemplates';
const SETTINGS_DOC_ID = '__design_settings__';

const DEFAULT_DESIGN_SETTINGS = {
  logoUrl: 'https://doxvl.se/logo-new.png',
  logoLinkUrl: 'https://doxvl.se',
  logoHeight: 53,
  logoAlign: 'center',
  headerBackground: '#2E2D2C',
  headerTextColor: '#ffffff',
  headerBorderColor: '#2E2D2C',
  showHeaderTitle: true,
  showLogo: true,
  primaryColor: '#0EB0A6',
  successColor: '#22c55e',
  dangerColor: '#ef4444',
  footerBackground: '#f8f9fa',
  footerTextColor: '#5f6368',
  companyName: 'DOX Visumpartner AB',
  companyTagline: 'Professionella visum- & legaliseringstjänster',
  companyTaglineEn: 'Professional visa & document legalisation services',
  autoGeneratedNote: 'Detta är ett automatiskt genererat meddelande.',
  autoGeneratedNoteEn: 'This is an automatically generated message.',
  contactEmail: 'info@doxvl.se',
  contactPhone: '08-40941900',
  postalAddress: 'DOX Visumpartner AB\nLivdjursgatan 4, våning 6\n121 62 Johanneshov',
  bodyMaxWidth: 600,
  borderRadius: 12,
  fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
};

const ESCAPE_HTML_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, ch => ESCAPE_HTML_MAP[ch]);
}

function substituteVariables(template, variables, variableSchema = []) {
  const isHtmlMap = new Map(variableSchema.map(v => [v.key, !!v.isHtml]));
  return template.replace(/\{\{(\w+)\}\}/g, (_m, key) => {
    const value = variables[key];
    if (value == null || value === '') return '';
    const str = String(value);
    return isHtmlMap.get(key) ? str : escapeHtml(str);
  });
}

function formatBodyAsHtml(body, htmlVariableKeys = new Set()) {
  if (!body) return '';
  if (/<\s*(p|div|table|h[1-6]|ul|ol|blockquote|hr|br)[\s>]/i.test(body)) return body;
  const paragraphs = body
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .map(p => p.trim())
    .filter(p => p.length > 0);
  return paragraphs.map(p => {
    const onlyVarMatch = p.match(/^\{\{(\w+)\}\}$/);
    if (onlyVarMatch && htmlVariableKeys.has(onlyVarMatch[1])) return p;
    return `<p>${p.replace(/\n/g, '<br>')}</p>`;
  }).join('\n');
}

function generateEmailWrapper({ settings: s, lang, title, headerTitle, headerSubtitle, bodyContent, showContactSection }) {
  const isEn = lang === 'en';
  const showContact = showContactSection !== false;
  const logoImg = s.showLogo ? `<img src="${s.logoUrl}" alt="${s.companyName}" height="${s.logoHeight}" style="height:${s.logoHeight}px;width:auto;border:0;outline:none;text-decoration:none;display:block;">` : '';
  const logoHtml = s.showLogo
    ? `<a href="${s.logoLinkUrl}" target="_blank" style="display:inline-block;text-decoration:none;border:0;outline:none;">${logoImg}</a>`
    : '';
  const contactHtml = showContact ? `
    <div style="background:#f0f9ff; border:1px solid #bae6fd; border-radius:8px; padding:18px; margin:22px 0; text-align:center;">
      <h3 style="margin:0 0 8px;">${isEn ? 'Questions?' : 'Har du frågor?'}</h3>
      <p style="margin:0;">${isEn ? 'Feel free to contact us:' : 'Kontakta oss gärna:'}</p>
      <p style="margin:8px 0 0;">📧 <a href="mailto:${s.contactEmail}" style="color:${s.primaryColor}">${s.contactEmail}</a> &nbsp; 📞 ${s.contactPhone}</p>
    </div>
  ` : '';
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
</head>
<body style="font-family:${s.fontFamily}; line-height:1.6; color:#202124; max-width:${s.bodyMaxWidth}px; margin:0 auto; background-color:#f8f9fa; padding:20px;">
  <div style="background-color:#ffffff; border-radius:${s.borderRadius}px; box-shadow:0 2px 6px rgba(0,0,0,0.08); overflow:hidden;">
    <div style="background:${s.headerBackground}; color:${s.headerTextColor}; padding:32px 36px 24px; text-align:${s.logoAlign}; border-bottom:2px solid ${s.headerBorderColor};">
      ${logoHtml}
      ${s.showHeaderTitle ? `<h1 style="margin:${s.showLogo ? '20px' : '0'} 0 0; font-size:22px; font-weight:700; letter-spacing:0.2px; color:${s.headerTextColor};">${headerTitle}</h1>` : ''}
      ${headerSubtitle && s.showHeaderTitle ? `<p style="color:${s.headerTextColor}; opacity:0.8; margin:8px 0 0;">${headerSubtitle}</p>` : ''}
    </div>
    <div style="padding:32px 36px;">
      ${bodyContent}
      ${contactHtml}
    </div>
    <div style="background:${s.footerBackground}; padding:24px 36px; text-align:center; border-top:1px solid #eaecef;">
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;"><strong>${s.companyName}</strong></p>
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;">${isEn ? s.companyTaglineEn : s.companyTagline}</p>
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;">${isEn ? s.autoGeneratedNoteEn : s.autoGeneratedNote}</p>
    </div>
  </div>
</body>
</html>`.trim();
}

async function getTemplate(id) {
  try {
    const snap = await admin.firestore().collection(COLLECTION).doc(id).get();
    if (!snap.exists) return null;
    return { id: snap.id, ...snap.data() };
  } catch (err) {
    console.warn(`[emailRenderer] Failed to load template "${id}"`, err);
    return null;
  }
}

async function getDesignSettings() {
  try {
    const snap = await admin.firestore().collection(COLLECTION).doc(SETTINGS_DOC_ID).get();
    if (!snap.exists) return DEFAULT_DESIGN_SETTINGS;
    return { ...DEFAULT_DESIGN_SETTINGS, ...snap.data() };
  } catch {
    return DEFAULT_DESIGN_SETTINGS;
  }
}

/**
 * Render an email from the catalog. Returns { subject, html, rendered }.
 * When `rendered` is false the caller should fall back to hardcoded defaults.
 */
async function renderEmail(templateId, variables, locale = 'sv', options = {}) {
  const template = await getTemplate(templateId);
  if (!template) return { subject: '', html: '', rendered: false };

  const settings = await getDesignSettings();
  const subjectTpl = locale === 'en' ? template.subjectEn : template.subjectSv;
  const bodyTpl = locale === 'en' ? template.bodyEn : template.bodySv;

  const subject = substituteVariables(subjectTpl || '', variables, template.variables);
  const htmlVarKeys = new Set((template.variables || []).filter(v => v.isHtml).map(v => v.key));
  const bodyFormatted = formatBodyAsHtml(bodyTpl || '', htmlVarKeys);
  const bodyContent = substituteVariables(bodyFormatted, variables, template.variables);

  const html = generateEmailWrapper({
    settings,
    lang: locale,
    title: subject,
    headerTitle: subject,
    bodyContent,
    showContactSection: options.showContactSection,
  });

  return { subject, html, rendered: true };
}

module.exports = { renderEmail };
