/**
 * Svensklistan Form Auto-fill Script Generator
 * 
 * Generates a JavaScript snippet that can be pasted into the browser console
 * on https://www.swedenabroad.se/sv/svensklistan/ to auto-fill the registration form.
 * 
 * Required data:
 * - firstName, lastName (from travelers)
 * - personnummer (collected via addon required field)
 * - destinationCountry (from order)
 * - cityInCountry (optional, collected via addon)
 * - arrivalDate (from departureDate)
 * - departureDate (from returnDateVisa)
 * - email (from customerInfo)
 * - phone (from customerInfo)
 */

export interface SvensklistanData {
  firstName: string;
  lastName: string;
  personnummer: string; // ÅÅÅÅMMDD-NNNN
  country: string; // Country name in Swedish
  countryCode: string; // ISO country code
  cityInCountry?: string;
  arrivalDate: string; // YYYY-MM-DD
  departureDate?: string; // YYYY-MM-DD (empty = 1 year)
  email: string;
  mobilePhone?: string; // Full number with country code
  homePhone?: string;
  employer?: string;
}

/**
 * Generate a JavaScript console script that auto-fills the Svensklistan form.
 * The admin pastes this into the browser console on the Svensklistan page.
 */
export function generateSvensklistanScript(data: SvensklistanData): string {
  // Escape strings for safe injection into JS
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');

  // Format phone: remove +46 prefix and leading 0 for Swedish numbers
  const formatPhone = (phone?: string): string => {
    if (!phone) return '';
    let p = phone.trim();
    // Remove spaces, dashes
    p = p.replace(/[\s-]/g, '');
    // If starts with +46, convert to 0-prefixed
    if (p.startsWith('+46')) {
      p = '0' + p.slice(3);
    }
    return p;
  };

  const mobileFormatted = formatPhone(data.mobilePhone);

  // Format arrival date from YYYY-MM-DD to the format the form expects
  const formatDateForForm = (dateStr: string): string => {
    if (!dateStr) return '';
    // The form likely uses a date picker, we'll set the value directly
    return dateStr; // YYYY-MM-DD
  };

  const script = `
// === Svensklistan Auto-fill Script ===
// Generated by DOX Visumpartner Admin
// Traveler: ${esc(data.firstName)} ${esc(data.lastName)}
// =====================================

(function() {
  'use strict';
  
  function setInputValue(selector, value) {
    const el = document.querySelector(selector);
    if (!el) { console.warn('Element not found:', selector); return false; }
    const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
    nativeInputValueSetter.call(el, value);
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
    el.dispatchEvent(new Event('blur', { bubbles: true }));
    return true;
  }

  function setTextareaValue(selector, value) {
    const el = document.querySelector(selector);
    if (!el) { console.warn('Element not found:', selector); return false; }
    const nativeTextareaSetter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set;
    nativeTextareaSetter.call(el, value);
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
    return true;
  }

  function selectDropdownByText(selector, text) {
    const el = document.querySelector(selector);
    if (!el) { console.warn('Select not found:', selector); return false; }
    const options = el.querySelectorAll('option');
    for (const opt of options) {
      if (opt.textContent.trim().toLowerCase().includes(text.toLowerCase())) {
        el.value = opt.value;
        el.dispatchEvent(new Event('change', { bubbles: true }));
        return true;
      }
    }
    console.warn('Option not found for:', text);
    return false;
  }

  function setCheckbox(selector, checked) {
    const el = document.querySelector(selector);
    if (!el) { console.warn('Checkbox not found:', selector); return false; }
    if (el.checked !== checked) {
      el.click();
    }
    return true;
  }

  function fillByLabel(labelText, value) {
    const labels = document.querySelectorAll('label');
    for (const label of labels) {
      if (label.textContent.trim().toLowerCase().includes(labelText.toLowerCase())) {
        const forAttr = label.getAttribute('for');
        if (forAttr) {
          const input = document.getElementById(forAttr);
          if (input) {
            if (input.tagName === 'SELECT') {
              selectDropdownByText('#' + forAttr, value);
              return true;
            }
            const nativeSetter = Object.getOwnPropertyDescriptor(
              input.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype, 
              'value'
            ).set;
            nativeSetter.call(input, value);
            input.dispatchEvent(new Event('input', { bubbles: true }));
            input.dispatchEvent(new Event('change', { bubbles: true }));
            return true;
          }
        }
        // Try sibling or parent input
        const container = label.closest('.form-group, .field, div');
        if (container) {
          const input = container.querySelector('input, select, textarea');
          if (input) {
            if (input.tagName === 'SELECT') {
              for (const opt of input.querySelectorAll('option')) {
                if (opt.textContent.trim().toLowerCase().includes(value.toLowerCase())) {
                  input.value = opt.value;
                  input.dispatchEvent(new Event('change', { bubbles: true }));
                  return true;
                }
              }
            } else {
              const nativeSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
              nativeSetter.call(input, value);
              input.dispatchEvent(new Event('input', { bubbles: true }));
              input.dispatchEvent(new Event('change', { bubbles: true }));
              return true;
            }
          }
        }
      }
    }
    console.warn('Field not found for label:', labelText);
    return false;
  }

  // Fill all fields
  const results = [];
  
  results.push(['Förnamn', fillByLabel('Förnamn', '${esc(data.firstName)}')]);
  results.push(['Efternamn', fillByLabel('Efternamn', '${esc(data.lastName)}')]);
  results.push(['Personnummer', fillByLabel('Personnummer', '${esc(data.personnummer)}')]);
  results.push(['Vistelseland', fillByLabel('Vistelseland', '${esc(data.country)}')]);
  ${data.cityInCountry ? `results.push(['Ort', fillByLabel('Ort', '${esc(data.cityInCountry)}')]);` : ''}
  results.push(['Ankomstdatum', fillByLabel('Ankomstdatum', '${esc(formatDateForForm(data.arrivalDate))}')]);
  ${data.departureDate ? `results.push(['Frånresedatum', fillByLabel('frånresedatum', '${esc(formatDateForForm(data.departureDate))}')]);` : ''}
  results.push(['E-postadress', fillByLabel('E-postadress', '${esc(data.email)}')]);
  ${mobileFormatted ? `results.push(['Mobilnummer', fillByLabel('Mobilnummer', '${esc(mobileFormatted)}')]);` : ''}
  ${data.employer ? `results.push(['Arbetsgivare', fillByLabel('Arbetsgivare', '${esc(data.employer)}')]);` : ''}

  // Try to check the consent checkbox
  const checkboxes = document.querySelectorAll('input[type="checkbox"]');
  for (const cb of checkboxes) {
    const label = cb.closest('label') || document.querySelector('label[for="' + cb.id + '"]');
    if (label && label.textContent.includes('införstådd')) {
      if (!cb.checked) cb.click();
      results.push(['Godkännande', true]);
      break;
    }
  }

  // Report results
  console.log('\\n=== Svensklistan Auto-fill Results ===');
  let success = 0, fail = 0;
  for (const [name, ok] of results) {
    if (ok) { success++; console.log('✅ ' + name); }
    else { fail++; console.log('❌ ' + name + ' - MANUAL INPUT NEEDED'); }
  }
  console.log('\\nFilled: ' + success + '/' + results.length);
  if (fail > 0) console.log('⚠️ ' + fail + ' field(s) need manual input');
  else console.log('✅ All fields filled! Review and click "Skicka in anmälan"');
  console.log('=====================================\\n');
  
  alert('Svensklistan auto-fill complete!\\n\\nFilled: ' + success + '/' + results.length + (fail > 0 ? '\\n⚠️ ' + fail + ' field(s) need manual input' : '\\n✅ All fields filled!') + '\\n\\nPlease review all fields before submitting.');
})();
`.trim();

  return script;
}

/**
 * Build SvensklistanData from order data
 */
export function buildSvensklistanDataFromOrder(order: any, travelerIndex: number): SvensklistanData | null {
  const travelers = order.travelers || [];
  const traveler = travelers[travelerIndex];
  if (!traveler) return null;

  // Get addon field data (personnummer, city, etc.)
  const addonData = order.addonFieldData || {};
  const travelerAddonData = addonData[`traveler_${travelerIndex}`] || addonData || {};

  // Get country name in Swedish from the order
  const countryName = order.destinationCountry || '';
  const countryCode = order.destinationCountryCode || '';

  return {
    firstName: traveler.firstName || '',
    lastName: traveler.lastName || '',
    personnummer: travelerAddonData.personnummer || traveler.personnummer || '',
    country: countryName,
    countryCode: countryCode,
    cityInCountry: travelerAddonData.cityInCountry || '',
    arrivalDate: order.departureDate || '',
    departureDate: order.returnDateVisa || '',
    email: order.customerInfo?.email || '',
    mobilePhone: order.customerInfo?.phone || '',
    employer: travelerAddonData.employer || '',
  };
}
