/**
 * DS-160 Form Template Definition
 * 
 * This file defines the form fields that will be displayed to customers
 * when filling out the DS-160 visa application form.
 */

import { FormField, FormFieldGroup } from '../../firebase/visaFormService';

// ============================================================
// FIELD GROUPS
// ============================================================

export const DS160_FIELD_GROUPS: FormFieldGroup[] = [
  {
    id: 'personal',
    label: 'Personuppgifter',
    labelEn: 'Personal Information',
    icon: 'user',
    sortOrder: 1,
  },
  {
    id: 'passport',
    label: 'Passuppgifter',
    labelEn: 'Passport Information',
    icon: 'id-card',
    sortOrder: 2,
  },
  {
    id: 'travel',
    label: 'Reseinformation',
    labelEn: 'Travel Information',
    icon: 'plane',
    sortOrder: 3,
  },
  {
    id: 'contact',
    label: 'Kontaktuppgifter',
    labelEn: 'Contact Information',
    icon: 'phone',
    sortOrder: 4,
  },
  {
    id: 'usContact',
    label: 'Kontakt i USA',
    labelEn: 'US Contact',
    icon: 'map-pin',
    sortOrder: 5,
  },
  {
    id: 'family',
    label: 'Familjeuppgifter',
    labelEn: 'Family Information',
    icon: 'users',
    sortOrder: 6,
  },
  {
    id: 'work',
    label: 'Arbete & Utbildning',
    labelEn: 'Work & Education',
    icon: 'briefcase',
    sortOrder: 7,
  },
  {
    id: 'previousTravel',
    label: 'Tidigare resor till USA',
    labelEn: 'Previous US Travel',
    icon: 'history',
    sortOrder: 8,
  },
  {
    id: 'additional',
    label: 'Ytterligare information',
    labelEn: 'Additional Information',
    icon: 'globe',
    sortOrder: 9,
  },
  {
    id: 'security',
    label: 'Säkerhetsfrågor',
    labelEn: 'Security Questions',
    icon: 'shield',
    sortOrder: 10,
  },
];

// ============================================================
// FORM FIELDS - PERSONAL INFORMATION
// ============================================================

const PERSONAL_FIELDS: FormField[] = [
  {
    id: 'surname',
    label: 'Efternamn (som i passet)',
    labelEn: 'Surname (as in passport)',
    type: 'text',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 1,
    prefillFrom: 'travelers[i].lastName',
  },
  {
    id: 'givenName',
    label: 'Förnamn (som i passet)',
    labelEn: 'Given Name (as in passport)',
    type: 'text',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 2,
    prefillFrom: 'travelers[i].firstName',
  },
  {
    id: 'fullNameNative',
    label: 'Fullständigt namn på modersmål (om annat alfabet)',
    labelEn: 'Full name in native alphabet (if different)',
    type: 'text',
    required: false,
    helpText: 'Lämna tomt om ditt modersmål använder latinska bokstäver',
    helpTextEn: 'Leave empty if your native language uses Latin letters',
    group: 'personal',
    perTraveler: true,
    sortOrder: 3,
  },
  {
    id: 'hasOtherNames',
    label: 'Har du använt andra namn?',
    labelEn: 'Have you used other names?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'personal',
    perTraveler: true,
    sortOrder: 4,
  },
  {
    id: 'otherSurname',
    label: 'Annat efternamn',
    labelEn: 'Other surname',
    type: 'text',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'personal',
    perTraveler: true,
    sortOrder: 5,
  },
  {
    id: 'otherGivenName',
    label: 'Annat förnamn',
    labelEn: 'Other given name',
    type: 'text',
    required: false,
    group: 'personal',
    perTraveler: true,
    sortOrder: 6,
  },
  {
    id: 'sex',
    label: 'Kön',
    labelEn: 'Sex',
    type: 'select',
    required: true,
    options: [
      { value: 'M', label: 'Man', labelEn: 'Male' },
      { value: 'F', label: 'Kvinna', labelEn: 'Female' },
    ],
    group: 'personal',
    perTraveler: true,
    sortOrder: 7,
  },
  {
    id: 'maritalStatus',
    label: 'Civilstånd',
    labelEn: 'Marital Status',
    type: 'select',
    required: true,
    options: [
      { value: 'SINGLE', label: 'Ogift', labelEn: 'Single' },
      { value: 'MARRIED', label: 'Gift', labelEn: 'Married' },
      { value: 'DIVORCED', label: 'Skild', labelEn: 'Divorced' },
      { value: 'WIDOWED', label: 'Änka/Änkling', labelEn: 'Widowed' },
      { value: 'SEPARATED', label: 'Separerad', labelEn: 'Separated' },
      { value: 'COMMON_LAW', label: 'Sambo', labelEn: 'Common Law Marriage' },
    ],
    group: 'personal',
    perTraveler: true,
    sortOrder: 8,
  },
  {
    id: 'dateOfBirth',
    label: 'Födelsedatum',
    labelEn: 'Date of Birth',
    type: 'date',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 9,
    prefillFrom: 'travelers[i].dateOfBirth',
  },
  {
    id: 'cityOfBirth',
    label: 'Födelseort',
    labelEn: 'City of Birth',
    type: 'text',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 10,
  },
  {
    id: 'countryOfBirth',
    label: 'Födelseland',
    labelEn: 'Country of Birth',
    type: 'text',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 11,
  },
  {
    id: 'nationality',
    label: 'Nationalitet',
    labelEn: 'Nationality',
    type: 'text',
    required: true,
    group: 'personal',
    perTraveler: true,
    sortOrder: 12,
    prefillFrom: 'nationality',
  },
  {
    id: 'hasOtherNationality',
    label: 'Har du annat medborgarskap?',
    labelEn: 'Do you have another nationality?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'personal',
    perTraveler: true,
    sortOrder: 13,
  },
  {
    id: 'otherNationality',
    label: 'Annat medborgarskap',
    labelEn: 'Other nationality',
    type: 'text',
    required: false,
    group: 'personal',
    perTraveler: true,
    sortOrder: 14,
  },
  {
    id: 'nationalIdNumber',
    label: 'Nationellt ID-nummer (personnummer)',
    labelEn: 'National ID Number',
    type: 'personnummer',
    required: false,
    helpText: 'Svenskt personnummer eller motsvarande',
    helpTextEn: 'Swedish personal number or equivalent',
    group: 'personal',
    perTraveler: true,
    sortOrder: 15,
  },
];

// ============================================================
// FORM FIELDS - PASSPORT INFORMATION
// ============================================================

const PASSPORT_FIELDS: FormField[] = [
  {
    id: 'passportType',
    label: 'Typ av pass',
    labelEn: 'Passport Type',
    type: 'select',
    required: true,
    options: [
      { value: 'REGULAR', label: 'Vanligt pass', labelEn: 'Regular' },
      { value: 'OFFICIAL', label: 'Tjänstepass', labelEn: 'Official' },
      { value: 'DIPLOMATIC', label: 'Diplomatpass', labelEn: 'Diplomatic' },
      { value: 'OTHER', label: 'Annat', labelEn: 'Other' },
    ],
    group: 'passport',
    perTraveler: true,
    sortOrder: 20,
  },
  {
    id: 'passportNumber',
    label: 'Passnummer',
    labelEn: 'Passport Number',
    type: 'text',
    required: true,
    group: 'passport',
    perTraveler: true,
    sortOrder: 21,
    prefillFrom: 'travelers[i].passportNumber',
  },
  {
    id: 'passportIssuingCountry',
    label: 'Utfärdande land',
    labelEn: 'Issuing Country',
    type: 'text',
    required: true,
    group: 'passport',
    perTraveler: true,
    sortOrder: 22,
  },
  {
    id: 'passportIssuingCity',
    label: 'Utfärdande stad/ort',
    labelEn: 'Issuing City',
    type: 'text',
    required: true,
    group: 'passport',
    perTraveler: true,
    sortOrder: 23,
  },
  {
    id: 'passportIssueDate',
    label: 'Utfärdandedatum',
    labelEn: 'Issue Date',
    type: 'date',
    required: true,
    group: 'passport',
    perTraveler: true,
    sortOrder: 24,
  },
  {
    id: 'passportExpiryDate',
    label: 'Utgångsdatum',
    labelEn: 'Expiry Date',
    type: 'date',
    required: true,
    group: 'passport',
    perTraveler: true,
    sortOrder: 25,
  },
  {
    id: 'hasLostPassport',
    label: 'Har du förlorat eller fått ett pass stulet?',
    labelEn: 'Have you ever lost a passport or had one stolen?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'passport',
    perTraveler: true,
    sortOrder: 26,
  },
  {
    id: 'lostPassportExplanation',
    label: 'Förklara vad som hände med det förlorade/stulna passet',
    labelEn: 'Explain what happened to the lost/stolen passport',
    type: 'textarea',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'passport',
    perTraveler: true,
    sortOrder: 27,
  },
];

// ============================================================
// FORM FIELDS - TRAVEL INFORMATION
// ============================================================

const TRAVEL_FIELDS: FormField[] = [
  {
    id: 'purposeOfTrip',
    label: 'Syfte med resan',
    labelEn: 'Purpose of Trip',
    type: 'select',
    required: true,
    options: [
      { value: 'B1/B2', label: 'Affärer/Turism (B1/B2)', labelEn: 'Business/Tourism (B1/B2)' },
      { value: 'B1', label: 'Affärer (B1)', labelEn: 'Business (B1)' },
      { value: 'B2', label: 'Turism (B2)', labelEn: 'Tourism (B2)' },
      { value: 'F1', label: 'Student (F1)', labelEn: 'Student (F1)' },
      { value: 'J1', label: 'Utbytesbesökare (J1)', labelEn: 'Exchange Visitor (J1)' },
      { value: 'C1/D', label: 'Transit/Besättning (C1/D)', labelEn: 'Transit/Crew (C1/D)' },
      { value: 'OTHER', label: 'Annat', labelEn: 'Other' },
    ],
    group: 'travel',
    perTraveler: false,
    sortOrder: 30,
  },
  {
    id: 'specificPurpose',
    label: 'Beskriv syftet med resan mer specifikt',
    labelEn: 'Describe the specific purpose of your trip',
    type: 'textarea',
    required: true,
    helpText: 'T.ex. "Affärsmöte med företag X" eller "Semester med familjen"',
    helpTextEn: 'E.g. "Business meeting with company X" or "Vacation with family"',
    group: 'travel',
    perTraveler: false,
    sortOrder: 31,
  },
  {
    id: 'hasSpecificTravelPlans',
    label: 'Har du specifika resplaner?',
    labelEn: 'Do you have specific travel plans?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'travel',
    perTraveler: false,
    sortOrder: 32,
  },
  {
    id: 'intendedArrivalDate',
    label: 'Planerat ankomstdatum',
    labelEn: 'Intended Arrival Date',
    type: 'date',
    required: true,
    group: 'travel',
    perTraveler: false,
    sortOrder: 33,
    prefillFrom: 'departureDate',
  },
  {
    id: 'intendedStayLength',
    label: 'Planerad vistelsetid',
    labelEn: 'Intended Length of Stay',
    type: 'text',
    required: true,
    placeholder: 'T.ex. 14',
    placeholderEn: 'E.g. 14',
    group: 'travel',
    perTraveler: false,
    sortOrder: 34,
  },
  {
    id: 'intendedStayUnit',
    label: 'Enhet för vistelsetid',
    labelEn: 'Length of Stay Unit',
    type: 'select',
    required: true,
    options: [
      { value: 'DAYS', label: 'Dagar', labelEn: 'Days' },
      { value: 'WEEKS', label: 'Veckor', labelEn: 'Weeks' },
      { value: 'MONTHS', label: 'Månader', labelEn: 'Months' },
    ],
    group: 'travel',
    perTraveler: false,
    sortOrder: 35,
  },
  {
    id: 'usStreetAddress',
    label: 'Adress i USA (hotell eller boende)',
    labelEn: 'US Address (hotel or accommodation)',
    type: 'text',
    required: true,
    helpText: 'Gatuadress där du kommer att bo',
    helpTextEn: 'Street address where you will stay',
    group: 'travel',
    perTraveler: false,
    sortOrder: 36,
  },
  {
    id: 'usCity',
    label: 'Stad i USA',
    labelEn: 'US City',
    type: 'text',
    required: true,
    group: 'travel',
    perTraveler: false,
    sortOrder: 37,
  },
  {
    id: 'usState',
    label: 'Delstat i USA',
    labelEn: 'US State',
    type: 'text',
    required: true,
    group: 'travel',
    perTraveler: false,
    sortOrder: 38,
  },
  {
    id: 'usZipCode',
    label: 'Postnummer i USA',
    labelEn: 'US Zip Code',
    type: 'text',
    required: false,
    group: 'travel',
    perTraveler: false,
    sortOrder: 39,
  },
  {
    id: 'whoPaysTripCost',
    label: 'Vem betalar för resan?',
    labelEn: 'Who is paying for your trip?',
    type: 'select',
    required: true,
    options: [
      { value: 'SELF', label: 'Jag själv', labelEn: 'Self' },
      { value: 'OTHER_PERSON', label: 'Annan person', labelEn: 'Other Person' },
      { value: 'COMPANY', label: 'Företag/Organisation', labelEn: 'Company/Organization' },
    ],
    group: 'travel',
    perTraveler: true,
    sortOrder: 40,
  },
  {
    id: 'payerName',
    label: 'Namn på betalare (om annan)',
    labelEn: 'Payer Name (if other)',
    type: 'text',
    required: false,
    helpText: 'Fyll i om någon annan betalar',
    helpTextEn: 'Fill in if someone else is paying',
    group: 'travel',
    perTraveler: true,
    sortOrder: 41,
  },
  {
    id: 'payerRelationship',
    label: 'Relation till betalare',
    labelEn: 'Relationship to Payer',
    type: 'text',
    required: false,
    group: 'travel',
    perTraveler: true,
    sortOrder: 42,
  },
];

// ============================================================
// FORM FIELDS - CONTACT INFORMATION
// ============================================================

const CONTACT_FIELDS: FormField[] = [
  {
    id: 'homeStreetAddress',
    label: 'Hemadress (gatuadress)',
    labelEn: 'Home Address (street)',
    type: 'text',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 50,
  },
  {
    id: 'homeCity',
    label: 'Stad',
    labelEn: 'City',
    type: 'text',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 51,
  },
  {
    id: 'homePostalCode',
    label: 'Postnummer',
    labelEn: 'Postal Code',
    type: 'text',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 52,
  },
  {
    id: 'homeCountry',
    label: 'Land',
    labelEn: 'Country',
    type: 'text',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 53,
  },
  {
    id: 'primaryPhone',
    label: 'Telefonnummer',
    labelEn: 'Phone Number',
    type: 'phone',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 54,
  },
  {
    id: 'email',
    label: 'E-postadress',
    labelEn: 'Email Address',
    type: 'email',
    required: true,
    group: 'contact',
    perTraveler: true,
    sortOrder: 55,
    prefillFrom: 'customerInfo.email',
  },
  {
    id: 'socialMediaPlatform1',
    label: 'Sociala medier - Plattform 1',
    labelEn: 'Social Media - Platform 1',
    type: 'select',
    required: false,
    options: [
      { value: 'NONE', label: 'Ingen', labelEn: 'None' },
      { value: 'FACEBOOK', label: 'Facebook', labelEn: 'Facebook' },
      { value: 'INSTAGRAM', label: 'Instagram', labelEn: 'Instagram' },
      { value: 'LINKEDIN', label: 'LinkedIn', labelEn: 'LinkedIn' },
      { value: 'TWITTER', label: 'Twitter/X', labelEn: 'Twitter/X' },
      { value: 'YOUTUBE', label: 'YouTube', labelEn: 'YouTube' },
      { value: 'OTHER', label: 'Annat', labelEn: 'Other' },
    ],
    helpText: 'DS-160 kräver information om sociala medier',
    helpTextEn: 'DS-160 requires social media information',
    group: 'contact',
    perTraveler: true,
    sortOrder: 56,
  },
  {
    id: 'socialMediaHandle1',
    label: 'Användarnamn på plattform 1',
    labelEn: 'Username on Platform 1',
    type: 'text',
    required: false,
    group: 'contact',
    perTraveler: true,
    sortOrder: 57,
  },
];

// ============================================================
// FORM FIELDS - US CONTACT
// ============================================================

const US_CONTACT_FIELDS: FormField[] = [
  {
    id: 'usContactName',
    label: 'Kontaktperson i USA - Namn',
    labelEn: 'US Contact Person - Name',
    type: 'text',
    required: true,
    helpText: 'Hotell, vän, familj eller affärskontakt',
    helpTextEn: 'Hotel, friend, family, or business contact',
    group: 'usContact',
    perTraveler: false,
    sortOrder: 60,
  },
  {
    id: 'usContactOrganization',
    label: 'Organisation/Företag',
    labelEn: 'Organization/Company',
    type: 'text',
    required: false,
    helpText: 'T.ex. hotellnamn eller företagsnamn',
    helpTextEn: 'E.g. hotel name or company name',
    group: 'usContact',
    perTraveler: false,
    sortOrder: 61,
  },
  {
    id: 'usContactRelationship',
    label: 'Relation till kontaktperson',
    labelEn: 'Relationship to Contact',
    type: 'text',
    required: true,
    placeholder: 'T.ex. Hotell, Vän, Affärskontakt',
    placeholderEn: 'E.g. Hotel, Friend, Business Contact',
    group: 'usContact',
    perTraveler: false,
    sortOrder: 62,
  },
  {
    id: 'usContactAddress',
    label: 'Kontaktpersonens adress',
    labelEn: 'Contact Address',
    type: 'text',
    required: true,
    group: 'usContact',
    perTraveler: false,
    sortOrder: 63,
  },
  {
    id: 'usContactPhone',
    label: 'Kontaktpersonens telefon',
    labelEn: 'Contact Phone',
    type: 'phone',
    required: true,
    group: 'usContact',
    perTraveler: false,
    sortOrder: 64,
  },
  {
    id: 'usContactEmail',
    label: 'Kontaktpersonens e-post',
    labelEn: 'Contact Email',
    type: 'email',
    required: false,
    group: 'usContact',
    perTraveler: false,
    sortOrder: 65,
  },
];

// ============================================================
// FORM FIELDS - FAMILY INFORMATION
// ============================================================

const FAMILY_FIELDS: FormField[] = [
  {
    id: 'fatherSurname',
    label: 'Faderns efternamn',
    labelEn: "Father's Surname",
    type: 'text',
    required: true,
    group: 'family',
    perTraveler: true,
    sortOrder: 70,
  },
  {
    id: 'fatherGivenName',
    label: 'Faderns förnamn',
    labelEn: "Father's Given Name",
    type: 'text',
    required: true,
    group: 'family',
    perTraveler: true,
    sortOrder: 71,
  },
  {
    id: 'fatherDateOfBirth',
    label: 'Faderns födelsedatum',
    labelEn: "Father's Date of Birth",
    type: 'date',
    required: false,
    helpText: 'Lämna tomt om okänt',
    helpTextEn: 'Leave empty if unknown',
    group: 'family',
    perTraveler: true,
    sortOrder: 72,
  },
  {
    id: 'isFatherInUS',
    label: 'Är din far i USA?',
    labelEn: 'Is your father in the US?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'family',
    perTraveler: true,
    sortOrder: 73,
  },
  {
    id: 'motherSurname',
    label: 'Moderns efternamn',
    labelEn: "Mother's Surname",
    type: 'text',
    required: true,
    group: 'family',
    perTraveler: true,
    sortOrder: 74,
  },
  {
    id: 'motherGivenName',
    label: 'Moderns förnamn',
    labelEn: "Mother's Given Name",
    type: 'text',
    required: true,
    group: 'family',
    perTraveler: true,
    sortOrder: 75,
  },
  {
    id: 'motherDateOfBirth',
    label: 'Moderns födelsedatum',
    labelEn: "Mother's Date of Birth",
    type: 'date',
    required: false,
    helpText: 'Lämna tomt om okänt',
    helpTextEn: 'Leave empty if unknown',
    group: 'family',
    perTraveler: true,
    sortOrder: 76,
  },
  {
    id: 'isMotherInUS',
    label: 'Är din mor i USA?',
    labelEn: 'Is your mother in the US?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'family',
    perTraveler: true,
    sortOrder: 77,
  },
  {
    id: 'hasImmediateRelativesInUS',
    label: 'Har du nära släktingar i USA?',
    labelEn: 'Do you have immediate relatives in the US?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    helpText: 'Make/maka, barn, syskon',
    helpTextEn: 'Spouse, children, siblings',
    group: 'family',
    perTraveler: true,
    sortOrder: 78,
  },
  {
    id: 'immediateRelativeDetails',
    label: 'Beskriv släktingar i USA',
    labelEn: 'Describe relatives in the US',
    type: 'textarea',
    required: false,
    helpText: 'Namn, relation och status (medborgare/permanent resident/etc)',
    helpTextEn: 'Name, relationship, and status (citizen/permanent resident/etc)',
    group: 'family',
    perTraveler: true,
    sortOrder: 79,
  },
  // Spouse info (conditional on marital status)
  {
    id: 'spouseSurname',
    label: 'Makes/makas efternamn',
    labelEn: "Spouse's Surname",
    type: 'text',
    required: false,
    helpText: 'Fyll i om du är gift',
    helpTextEn: 'Fill in if married',
    group: 'family',
    perTraveler: true,
    sortOrder: 80,
  },
  {
    id: 'spouseGivenName',
    label: 'Makes/makas förnamn',
    labelEn: "Spouse's Given Name",
    type: 'text',
    required: false,
    group: 'family',
    perTraveler: true,
    sortOrder: 81,
  },
  {
    id: 'spouseDateOfBirth',
    label: 'Makes/makas födelsedatum',
    labelEn: "Spouse's Date of Birth",
    type: 'date',
    required: false,
    group: 'family',
    perTraveler: true,
    sortOrder: 82,
  },
  {
    id: 'spouseNationality',
    label: 'Makes/makas nationalitet',
    labelEn: "Spouse's Nationality",
    type: 'text',
    required: false,
    group: 'family',
    perTraveler: true,
    sortOrder: 83,
  },
];

// ============================================================
// FORM FIELDS - WORK & EDUCATION
// ============================================================

const WORK_FIELDS: FormField[] = [
  {
    id: 'primaryOccupation',
    label: 'Nuvarande yrke/sysselsättning',
    labelEn: 'Current Occupation',
    type: 'select',
    required: true,
    options: [
      { value: 'EMPLOYED', label: 'Anställd', labelEn: 'Employed' },
      { value: 'SELF_EMPLOYED', label: 'Egenföretagare', labelEn: 'Self-Employed' },
      { value: 'STUDENT', label: 'Student', labelEn: 'Student' },
      { value: 'RETIRED', label: 'Pensionär', labelEn: 'Retired' },
      { value: 'UNEMPLOYED', label: 'Arbetslös', labelEn: 'Unemployed' },
      { value: 'HOMEMAKER', label: 'Hemmafru/-man', labelEn: 'Homemaker' },
      { value: 'OTHER', label: 'Annat', labelEn: 'Other' },
    ],
    group: 'work',
    perTraveler: true,
    sortOrder: 90,
  },
  {
    id: 'employerName',
    label: 'Arbetsgivare/Skola',
    labelEn: 'Employer/School Name',
    type: 'text',
    required: false,
    helpText: 'Fyll i om du är anställd eller student',
    helpTextEn: 'Fill in if employed or student',
    group: 'work',
    perTraveler: true,
    sortOrder: 91,
  },
  {
    id: 'employerAddress',
    label: 'Arbetsgivarens/Skolans adress',
    labelEn: 'Employer/School Address',
    type: 'text',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 92,
  },
  {
    id: 'employerCity',
    label: 'Stad',
    labelEn: 'City',
    type: 'text',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 93,
  },
  {
    id: 'employerCountry',
    label: 'Land',
    labelEn: 'Country',
    type: 'text',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 94,
  },
  {
    id: 'employerPhone',
    label: 'Arbetsgivarens telefon',
    labelEn: 'Employer Phone',
    type: 'phone',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 95,
  },
  {
    id: 'jobTitle',
    label: 'Befattning/Titel',
    labelEn: 'Job Title',
    type: 'text',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 96,
  },
  {
    id: 'employerStartDate',
    label: 'Anställningsdatum',
    labelEn: 'Employment Start Date',
    type: 'date',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 97,
  },
  {
    id: 'monthlyIncome',
    label: 'Månadsinkomst (SEK)',
    labelEn: 'Monthly Income (SEK)',
    type: 'text',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 98,
  },
  {
    id: 'jobDuties',
    label: 'Beskriv dina arbetsuppgifter',
    labelEn: 'Describe your job duties',
    type: 'textarea',
    required: false,
    group: 'work',
    perTraveler: true,
    sortOrder: 99,
  },
];

// ============================================================
// FORM FIELDS - PREVIOUS US TRAVEL
// ============================================================

const PREVIOUS_TRAVEL_FIELDS: FormField[] = [
  {
    id: 'hasBeenToUS',
    label: 'Har du tidigare besökt USA?',
    labelEn: 'Have you ever been to the US?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 100,
  },
  {
    id: 'lastUSVisitDate',
    label: 'Datum för senaste besök i USA',
    labelEn: 'Date of last US visit',
    type: 'date',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 101,
  },
  {
    id: 'lastUSVisitLength',
    label: 'Längd på senaste besök',
    labelEn: 'Length of last visit',
    type: 'text',
    required: false,
    placeholder: 'T.ex. 14 dagar, 3 månader',
    placeholderEn: 'E.g. 14 days, 3 months',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 102,
  },
  {
    id: 'hasUSDriversLicense',
    label: 'Har du eller har du haft amerikanskt körkort?',
    labelEn: 'Do you have or have you had a US driver\'s license?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 103,
  },
  {
    id: 'usDriversLicenseState',
    label: 'Vilken delstat utfärdade körkortet?',
    labelEn: 'Which state issued the license?',
    type: 'text',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 104,
  },
  {
    id: 'hasHadUSVisa',
    label: 'Har du tidigare haft amerikanskt visum?',
    labelEn: 'Have you ever had a US visa?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 105,
  },
  {
    id: 'previousVisaIssueDate',
    label: 'Datum då visumet utfärdades',
    labelEn: 'Date visa was issued',
    type: 'date',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 106,
  },
  {
    id: 'previousVisaNumber',
    label: 'Visumnummer (8 siffror)',
    labelEn: 'Visa number (8 digits)',
    type: 'text',
    required: false,
    helpText: 'Röda siffror längst ner till höger på visumet',
    helpTextEn: 'Red numbers at bottom right of visa',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 107,
  },
  {
    id: 'isSameVisaType',
    label: 'Ansöker du om samma typ av visum?',
    labelEn: 'Are you applying for the same type of visa?',
    type: 'select',
    required: false,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 108,
  },
  {
    id: 'hasVisaBeenLostStolen',
    label: 'Har ditt visum förlorats eller stulits?',
    labelEn: 'Has your visa been lost or stolen?',
    type: 'select',
    required: false,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 109,
  },
  {
    id: 'hasBeenRefusedVisa',
    label: 'Har du nekats amerikanskt visum eller inresa?',
    labelEn: 'Have you ever been refused a US visa or entry?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 110,
  },
  {
    id: 'visaRefusalExplanation',
    label: 'Förklara varför visum nekades',
    labelEn: 'Explain why visa was refused',
    type: 'textarea',
    required: false,
    helpText: 'Fyll i om du svarat ja ovan',
    helpTextEn: 'Fill in if you answered yes above',
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 111,
  },
  {
    id: 'hasImmigrantPetition',
    label: 'Har någon lämnat in en immigrantpetition för dig?',
    labelEn: 'Has anyone filed an immigrant petition for you?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'previousTravel',
    perTraveler: true,
    sortOrder: 112,
  },
];

// ============================================================
// FORM FIELDS - ADDITIONAL INFORMATION
// ============================================================

const ADDITIONAL_FIELDS: FormField[] = [
  {
    id: 'hasAttendedEducation',
    label: 'Har du gått på gymnasium eller högre utbildning?',
    labelEn: 'Have you attended secondary school or higher?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'additional',
    perTraveler: true,
    sortOrder: 120,
  },
  {
    id: 'educationInstitutionName',
    label: 'Namn på skola/universitet',
    labelEn: 'Name of school/university',
    type: 'text',
    required: false,
    helpText: 'Senaste utbildning',
    helpTextEn: 'Most recent education',
    group: 'additional',
    perTraveler: true,
    sortOrder: 121,
  },
  {
    id: 'educationCity',
    label: 'Stad',
    labelEn: 'City',
    type: 'text',
    required: false,
    group: 'additional',
    perTraveler: true,
    sortOrder: 122,
  },
  {
    id: 'educationCountry',
    label: 'Land',
    labelEn: 'Country',
    type: 'text',
    required: false,
    group: 'additional',
    perTraveler: true,
    sortOrder: 123,
  },
  {
    id: 'educationCourseOfStudy',
    label: 'Utbildningsinriktning',
    labelEn: 'Course of study',
    type: 'text',
    required: false,
    placeholder: 'T.ex. Ekonomi, Teknik, Medicin',
    placeholderEn: 'E.g. Business, Engineering, Medicine',
    group: 'additional',
    perTraveler: true,
    sortOrder: 124,
  },
  {
    id: 'educationDateFrom',
    label: 'Startdatum',
    labelEn: 'Start date',
    type: 'date',
    required: false,
    group: 'additional',
    perTraveler: true,
    sortOrder: 125,
  },
  {
    id: 'educationDateTo',
    label: 'Slutdatum',
    labelEn: 'End date',
    type: 'date',
    required: false,
    group: 'additional',
    perTraveler: true,
    sortOrder: 126,
  },
  {
    id: 'languagesSpoken',
    label: 'Vilka språk talar du?',
    labelEn: 'What languages do you speak?',
    type: 'text',
    required: true,
    placeholder: 'T.ex. Svenska, Engelska, Spanska',
    placeholderEn: 'E.g. Swedish, English, Spanish',
    group: 'additional',
    perTraveler: true,
    sortOrder: 127,
  },
  {
    id: 'hasTraveledLast5Years',
    label: 'Har du rest till andra länder de senaste 5 åren?',
    labelEn: 'Have you traveled to other countries in the last 5 years?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'additional',
    perTraveler: true,
    sortOrder: 128,
  },
  {
    id: 'countriesVisitedLast5Years',
    label: 'Vilka länder har du besökt?',
    labelEn: 'Which countries have you visited?',
    type: 'textarea',
    required: false,
    helpText: 'Lista länderna separerade med komma',
    helpTextEn: 'List countries separated by comma',
    group: 'additional',
    perTraveler: true,
    sortOrder: 129,
  },
  {
    id: 'belongsToOrganizations',
    label: 'Tillhör du några organisationer eller föreningar?',
    labelEn: 'Do you belong to any organizations or associations?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'additional',
    perTraveler: true,
    sortOrder: 130,
  },
  {
    id: 'organizationNames',
    label: 'Namn på organisationer',
    labelEn: 'Organization names',
    type: 'textarea',
    required: false,
    helpText: 'Professionella, sociala eller välgörenhetsorganisationer',
    helpTextEn: 'Professional, social, or charitable organizations',
    group: 'additional',
    perTraveler: true,
    sortOrder: 131,
  },
  {
    id: 'hasServedInMilitary',
    label: 'Har du gjort militärtjänst?',
    labelEn: 'Have you ever served in the military?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'additional',
    perTraveler: true,
    sortOrder: 132,
  },
  {
    id: 'militaryDetails',
    label: 'Detaljer om militärtjänst',
    labelEn: 'Military service details',
    type: 'textarea',
    required: false,
    helpText: 'Land, förband, rang, datum',
    helpTextEn: 'Country, branch, rank, dates',
    group: 'additional',
    perTraveler: true,
    sortOrder: 133,
  },
];

// ============================================================
// FORM FIELDS - SECURITY QUESTIONS (SIMPLIFIED)
// ============================================================

const SECURITY_FIELDS: FormField[] = [
  {
    id: 'securityDisease',
    label: 'Har du en smittsam sjukdom?',
    labelEn: 'Do you have a communicable disease?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'security',
    perTraveler: true,
    sortOrder: 110,
  },
  {
    id: 'securityCriminal',
    label: 'Har du blivit arresterad eller dömd för brott?',
    labelEn: 'Have you been arrested or convicted of a crime?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'security',
    perTraveler: true,
    sortOrder: 111,
  },
  {
    id: 'securityDrugs',
    label: 'Har du brutit mot lagar om droger?',
    labelEn: 'Have you violated drug laws?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'security',
    perTraveler: true,
    sortOrder: 112,
  },
  {
    id: 'securityTerrorism',
    label: 'Har du kopplingar till terrorism?',
    labelEn: 'Do you have any ties to terrorism?',
    type: 'select',
    required: true,
    options: [
      { value: 'no', label: 'Nej', labelEn: 'No' },
      { value: 'yes', label: 'Ja', labelEn: 'Yes' },
    ],
    group: 'security',
    perTraveler: true,
    sortOrder: 113,
  },
  {
    id: 'securityExplanation',
    label: 'Förklaring (om du svarat ja på någon säkerhetsfråga)',
    labelEn: 'Explanation (if you answered yes to any security question)',
    type: 'textarea',
    required: false,
    group: 'security',
    perTraveler: true,
    sortOrder: 114,
  },
];

// ============================================================
// COMBINED FIELDS
// ============================================================

export const DS160_FORM_FIELDS: FormField[] = [
  ...PERSONAL_FIELDS,
  ...PASSPORT_FIELDS,
  ...TRAVEL_FIELDS,
  ...CONTACT_FIELDS,
  ...US_CONTACT_FIELDS,
  ...FAMILY_FIELDS,
  ...WORK_FIELDS,
  ...PREVIOUS_TRAVEL_FIELDS,
  ...ADDITIONAL_FIELDS,
  ...SECURITY_FIELDS,
];

// ============================================================
// TEMPLATE CREATION HELPER
// ============================================================

export function createDS160FormTemplate(): {
  name: string;
  nameEn: string;
  countryCode: string;
  visaCategory: string;
  visaProductId: string;
  groups: FormFieldGroup[];
  fields: FormField[];
} {
  return {
    name: 'USA DS-160 Visumansökan',
    nameEn: 'USA DS-160 Visa Application',
    countryCode: 'US',
    visaCategory: 'all',
    visaProductId: 'all',
    groups: DS160_FIELD_GROUPS,
    fields: DS160_FORM_FIELDS,
  };
}
