/**
 * USA ESTA Form Auto-fill Script Generator
 *
 * Generates JavaScript snippets for the ESTA application portal at
 * https://esta.cbp.dhs.gov
 *
 * The ESTA portal is an Angular application. Form fields use Angular's
 * reactive forms, so we need to trigger Angular change detection after
 * setting values.
 *
 * The application has one main page with all fields visible.
 * Admin navigates to the page, pastes the script in the browser console → auto-fill.
 */

// ============================================================
// DATA TYPE
// ============================================================

export interface ESTAData {
  // === Passport & Identity ===
  familyName: string;              // As on passport
  firstName: string;               // All given names as on passport
  passportNumber: string;          // 6-10 chars
  issuingCountry: string;          // Country code: "SE" for Sweden, "NO" for Norway, etc.
  citizenshipCountry: string;      // Country code: "SE", "NO", etc.
  gender: 'M' | 'F';

  // === Dates (use numeric strings WITHOUT leading zeros) ===
  // Date of Birth
  birthDay: string;                // "1"–"31"
  birthMonth: string;              // "1"–"12"
  birthYear: string;               // e.g. "1990"

  // Passport Issuance Date
  issueDay: string;                // "1"–"31"
  issueMonth: string;              // "1"–"12"
  issueYear: string;               // e.g. "2020"

  // Passport Expiration Date
  expiryDay: string;               // "1"–"31"
  expiryMonth: string;             // "1"–"12"
  expiryYear: string;              // e.g. "2030"

  // === Personal Details ===
  cityOfBirth: string;
  countryOfBirth: string;          // Country code: "SE", etc.

  // === Optional ID numbers (may be disabled depending on country) ===
  nationalIdNumber?: string;       // National ID number
  personalIdNumber?: string;       // Personal ID number (e.g. personnummer)

  // === Contact & Address (if on same page) ===
  email?: string;
  confirmEmail?: string;
  phoneCountryCode?: string;       // e.g. "46"
  phoneNumber?: string;

  // === Address ===
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  countryOfResidence?: string;     // Country code

  // === US Contact / Accommodation ===
  usAddressLine1?: string;
  usCity?: string;
  usState?: string;                // State code: "NY", "CA", etc.

  // === Employment ===
  employerName?: string;
  employerPhone?: string;
  employerAddressLine1?: string;
  employerCity?: string;
  employerState?: string;
  employerCountry?: string;        // Country code

  // === Eligibility questions (all should be "No" for ESTA approval) ===
  // These are Yes/No radio buttons on the form
}

// ============================================================
// SCRIPT PARTS
// ============================================================

const SCRIPT_HEADER = `
// === USA ESTA Auto-fill Script ===
// Generated by DOX Visumpartner Admin
// ===================================

(function() {
  'use strict';

  function findEl(selectorStr) {
    var parts = selectorStr.split(',');
    for (var i = 0; i < parts.length; i++) {
      var el = document.querySelector(parts[i].trim());
      if (el) return el;
    }
    return null;
  }

  // Set value on Angular input — triggers proper change detection
  function setVal(selector, value) {
    var el = findEl(selector);
    if (!el) { console.warn('Not found:', selector); return false; }
    // Use native setter to bypass Angular
    var proto = el.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    var setter = Object.getOwnPropertyDescriptor(proto, 'value');
    if (setter && setter.set) { setter.set.call(el, value); }
    else { el.value = value; }
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
    el.dispatchEvent(new Event('blur', { bubbles: true }));
    // Trigger Angular ngModel update
    el.dispatchEvent(new Event('keyup', { bubbles: true }));
    el.dispatchEvent(new Event('keydown', { bubbles: true }));
    return true;
  }

  // Set value on Angular select — must trigger Angular change detection
  function setSelect(selector, value) {
    var el = findEl(selector);
    if (!el) { console.warn('Select not found:', selector); return false; }
    // Try exact value match first
    for (var i = 0; i < el.options.length; i++) {
      if (el.options[i].value === value) {
        el.selectedIndex = i;
        el.dispatchEvent(new Event('change', { bubbles: true }));
        el.dispatchEvent(new Event('input', { bubbles: true }));
        // MDL selectfield update
        var container = el.closest('.mdl-selectfield');
        if (container) container.classList.add('is-dirty');
        return true;
      }
    }
    // Try text match (case-insensitive)
    var upperVal = value.toUpperCase();
    for (var i = 0; i < el.options.length; i++) {
      var optTxt = el.options[i].text.trim().toUpperCase();
      if (optTxt === upperVal || optTxt.includes(upperVal)) {
        el.selectedIndex = i;
        el.dispatchEvent(new Event('change', { bubbles: true }));
        el.dispatchEvent(new Event('input', { bubbles: true }));
        var container2 = el.closest('.mdl-selectfield');
        if (container2) container2.classList.add('is-dirty');
        return true;
      }
    }
    console.warn('Option not found:', value, 'in', selector);
    return false;
  }

  function setRadio(name, value) {
    var radios = document.querySelectorAll('input[name="' + name + '"]');
    for (var i = 0; i < radios.length; i++) {
      if (radios[i].value === value || radios[i].value.toUpperCase() === value.toUpperCase()) {
        radios[i].checked = true;
        radios[i].click();
        radios[i].dispatchEvent(new Event('change', { bubbles: true }));
        radios[i].dispatchEvent(new Event('input', { bubbles: true }));
        return true;
      }
    }
    console.warn('Radio not found:', name, '=', value);
    return false;
  }

  function setCheckbox(selector, checked) {
    var el = findEl(selector);
    if (!el) { console.warn('Checkbox not found:', selector); return false; }
    if (el.checked !== checked) { el.click(); }
    return true;
  }

  // Mark MDL textfield as dirty so floating label moves up
  function markDirty(selector) {
    var el = findEl(selector);
    if (!el) return;
    var container = el.closest('.mdl-textfield') || el.closest('.mdl-selectfield');
    if (container) {
      container.classList.add('is-dirty');
      container.classList.remove('is-invalid');
    }
  }

  var results = [];
  function r(name, ok) { results.push([name, ok]); }
`;

const SCRIPT_FOOTER = `
  // Mark all filled fields as dirty for MDL styling
  setTimeout(function() {
    document.querySelectorAll('.mdl-textfield__input, .mdl-selectfield__select').forEach(function(el) {
      if (el.value) {
        var container = el.closest('.mdl-textfield') || el.closest('.mdl-selectfield');
        if (container) container.classList.add('is-dirty');
      }
    });

    // Show results
    var success = 0, fail = 0;
    for (var i = 0; i < results.length; i++) {
      if (results[i][1]) { success++; console.log('\\u2705 ' + results[i][0]); }
      else { fail++; console.log('\\u274C ' + results[i][0] + ' \\u2014 CHECK MANUALLY'); }
    }
    var msg = 'ESTA auto-fill done!\\n\\nFilled: ' + success + '/' + results.length;
    if (fail > 0) msg += '\\n\\n\\u26A0\\uFE0F ' + fail + ' field(s) need manual review.';
    msg += '\\n\\nReview ALL fields before clicking Next.';
    alert(msg);
  }, 800);
})();
`;

function esc(s: string): string {
  return (s || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

/**
 * Generate the ESTA passport & personal info autofill script.
 *
 * This fills the main application page with passport details,
 * personal information, and dates.
 */
export function generateESTAScript(data: ESTAData): string {
  return `${SCRIPT_HEADER}
  // === ESTA APPLICATION ===
  // Traveler: ${esc(data.firstName)} ${esc(data.familyName)}
  // Passport: ${esc(data.passportNumber)}

  // --- Names ---
  r('Family Name', setVal('#applicantLastName', '${esc(data.familyName)}'));
  markDirty('#applicantLastName');

  r('First Name', setVal('#applicantFirstName', '${esc(data.firstName)}'));
  markDirty('#applicantFirstName');

  // --- Passport ---
  r('Passport Number', setVal('#passportNum', '${esc(data.passportNumber.toUpperCase())}'));
  markDirty('#passportNum');

  r('Issuing Country', setSelect('#issueCountry', '${esc(data.issuingCountry)}'));

  // Issuance Date (values without leading zeros: "1"-"31", "1"-"12")
  r('Issue Day', setSelect('#day_issueDate', '${esc(data.issueDay)}'));
  r('Issue Month', setSelect('#month_issueDate', '${esc(data.issueMonth)}'));
  r('Issue Year', setSelect('#year_issueDate', '${esc(data.issueYear)}'));

  // Expiration Date
  r('Expiry Day', setSelect('#day_expDate', '${esc(data.expiryDay)}'));
  r('Expiry Month', setSelect('#month_expDate', '${esc(data.expiryMonth)}'));
  r('Expiry Year', setSelect('#year_expDate', '${esc(data.expiryYear)}'));

  // --- Citizenship ---
  r('Citizenship', setSelect('#citizenshipCountry', '${esc(data.citizenshipCountry)}'));

  // --- National / Personal ID (may be disabled depending on country) ---
  ${data.nationalIdNumber ? `
  (function() {
    var natId = document.querySelector('#natIdNum');
    if (natId && !natId.disabled) {
      r('National ID', setVal('#natIdNum', '${esc(data.nationalIdNumber)}'));
      markDirty('#natIdNum');
    }
  })();` : '// National ID: not provided'}

  ${data.personalIdNumber ? `
  (function() {
    var persId = document.querySelector('#personalIdNum');
    if (persId && !persId.disabled) {
      r('Personal ID', setVal('#personalIdNum', '${esc(data.personalIdNumber)}'));
      markDirty('#personalIdNum');
    }
  })();` : '// Personal ID: not provided'}

  // --- Gender ---
  r('Gender', setSelect('#gender', '${esc(data.gender)}'));

  // --- Date of Birth ---
  r('Birth Day', setSelect('#day_birthday', '${esc(data.birthDay)}'));
  r('Birth Month', setSelect('#month_birthday', '${esc(data.birthMonth)}'));
  r('Birth Year', setSelect('#year_birthday', '${esc(data.birthYear)}'));

  // --- City & Country of Birth ---
  r('City of Birth', setVal('#cityOfBirth, [name="cityOfBirth"]', '${esc(data.cityOfBirth)}'));
  markDirty('#cityOfBirth');

  r('Country of Birth', setSelect('#countryOfBirth, [name="countryOfBirth"]', '${esc(data.countryOfBirth)}'));

  ${data.email ? `
  // --- Contact ---
  r('Email', setVal('#email, [name="email"]', '${esc(data.email)}'));
  markDirty('#email');
  r('Confirm Email', setVal('#confirmEmail, [name="confirmEmail"]', '${esc(data.confirmEmail || data.email)}'));
  markDirty('#confirmEmail');` : '// Email: not provided (may be on next step)'}

  ${data.phoneNumber ? `
  // --- Phone ---
  ${data.phoneCountryCode ? `r('Phone Country Code', setSelect('#phoneCountryCode, [name="phoneCountryCode"]', '${esc(data.phoneCountryCode)}'));` : ''}
  r('Phone Number', setVal('#phoneNumber, [name="phoneNumber"]', '${esc(data.phoneNumber)}'));
  markDirty('#phoneNumber');` : '// Phone: not provided (may be on next step)'}

  ${data.addressLine1 ? `
  // --- Home Address ---
  r('Address Line 1', setVal('#addressLine1, [name="addressLine1"]', '${esc(data.addressLine1)}'));
  markDirty('#addressLine1');
  ${data.addressLine2 ? `r('Address Line 2', setVal('#addressLine2, [name="addressLine2"]', '${esc(data.addressLine2)}'));
  markDirty('#addressLine2');` : ''}
  ${data.city ? `r('City', setVal('#city, [name="city"]', '${esc(data.city)}'));
  markDirty('#city');` : ''}
  ${data.state ? `r('State', setVal('#state, [name="state"]', '${esc(data.state)}'));
  markDirty('#state');` : ''}
  ${data.countryOfResidence ? `r('Country of Residence', setSelect('#countryOfResidence, [name="countryOfResidence"]', '${esc(data.countryOfResidence)}'));` : ''}` : '// Address: not provided (may be on next step)'}

  ${data.usAddressLine1 ? `
  // --- US Contact Address ---
  r('US Address', setVal('#usAddressLine1, [name="usAddressLine1"]', '${esc(data.usAddressLine1)}'));
  markDirty('#usAddressLine1');
  ${data.usCity ? `r('US City', setVal('#usCity, [name="usCity"]', '${esc(data.usCity)}'));
  markDirty('#usCity');` : ''}
  ${data.usState ? `r('US State', setSelect('#usState, [name="usState"]', '${esc(data.usState)}'));` : ''}` : '// US Address: not provided (may be on next step)'}

  ${data.employerName ? `
  // --- Employment ---
  r('Employer', setVal('#employerName, [name="employerName"]', '${esc(data.employerName)}'));
  markDirty('#employerName');
  ${data.employerPhone ? `r('Employer Phone', setVal('#employerPhone, [name="employerPhone"]', '${esc(data.employerPhone)}'));
  markDirty('#employerPhone');` : ''}
  ${data.employerAddressLine1 ? `r('Employer Address', setVal('#employerAddressLine1, [name="employerAddressLine1"]', '${esc(data.employerAddressLine1)}'));
  markDirty('#employerAddressLine1');` : ''}
  ${data.employerCity ? `r('Employer City', setVal('#employerCity, [name="employerCity"]', '${esc(data.employerCity)}'));
  markDirty('#employerCity');` : ''}
  ${data.employerCountry ? `r('Employer Country', setSelect('#employerCountry, [name="employerCountry"]', '${esc(data.employerCountry)}'));` : ''}` : '// Employment: not provided (may be on next step)'}

${SCRIPT_FOOTER}`;
}

/**
 * Generate script to set all eligibility questions to "No".
 * ESTA has 9 yes/no eligibility questions — all must be "No" for approval.
 * Run this after the main script if eligibility questions are on a separate step.
 */
export function generateEligibilityScript(): string {
  return `${SCRIPT_HEADER}
  // === ESTA ELIGIBILITY QUESTIONS ===
  // Setting all 9 questions to "No"

  // Find all Yes/No radio groups and select "No" for each
  var radioGroups = {};
  document.querySelectorAll('input[type="radio"]').forEach(function(radio) {
    var name = radio.getAttribute('name');
    if (name && !radioGroups[name]) {
      radioGroups[name] = true;
    }
  });

  var groupNames = Object.keys(radioGroups);
  console.log('Found ' + groupNames.length + ' radio groups');

  groupNames.forEach(function(name) {
    var radios = document.querySelectorAll('input[name="' + name + '"]');
    var noRadio = null;
    radios.forEach(function(radio) {
      // Look for the "No" option — value "N", "no", "false", "0", or label containing "No"
      var val = radio.value.toUpperCase();
      if (val === 'N' || val === 'NO' || val === 'FALSE' || val === '0') {
        noRadio = radio;
      }
      if (!noRadio) {
        var lbl = radio.closest('label') || document.querySelector('label[for="' + radio.id + '"]');
        if (lbl && lbl.textContent.trim().toUpperCase() === 'NO') {
          noRadio = radio;
        }
      }
    });
    if (noRadio) {
      noRadio.checked = true;
      noRadio.click();
      noRadio.dispatchEvent(new Event('change', { bubbles: true }));
      noRadio.dispatchEvent(new Event('input', { bubbles: true }));
      r(name + ' → No', true);
    } else {
      r(name + ' → No', false);
    }
  });

${SCRIPT_FOOTER}`;
}

/**
 * Generate all ESTA scripts — returns main form + eligibility scripts.
 */
export function generateAllESTAScripts(data: ESTAData): {
  main: string;
  eligibility: string;
} {
  return {
    main: generateESTAScript(data),
    eligibility: generateEligibilityScript(),
  };
}
