/**
 * Email Template Service
 *
 * Stores editable email template overrides in Firestore.
 * When sending emails, check here first — fall back to hardcoded templates if no override exists.
 */

import {
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from './config';

// ============================================================
// TYPES
// ============================================================

export type EmailCategory =
  | 'order-confirmation'
  | 'visa-status'
  | 'document-handling'
  | 'shipping'
  | 'billing'
  | 'custom'
  | 'internal';

export type EmailTrigger =
  | 'automatic'   // Fires automatically on event
  | 'manual'      // Admin clicks a button to send
  | 'scheduled';  // Sent on a schedule/cron

export interface EmailTemplateVariable {
  key: string;        // e.g. "customerName"
  description: string; // e.g. "Kundens förnamn"
  example: string;     // e.g. "Erik"
  isHtml?: boolean;    // when true, value is inserted raw (no HTML escaping)
}

export interface EmailTemplate {
  id: string;
  name: string;                // Display name, e.g. "Orderbekräftelse"
  nameEn: string;              // English name
  description: string;         // When/why this email is sent (Swedish)
  descriptionEn: string;       // English description
  category: EmailCategory;
  trigger: EmailTrigger;
  triggerEvent: string;        // Technical event, e.g. "order.created", "visa.approved"

  // Process map positioning
  processStep: number;         // Order in the process flow (1-based)
  processGroup: string;        // Group label, e.g. "Beställning", "Handläggning"

  // Template content (editable)
  subjectSv: string;
  subjectEn: string;
  bodySv: string;              // HTML body or key text blocks (Swedish)
  bodyEn: string;              // HTML body or key text blocks (English)

  // Available variables for this template
  variables: EmailTemplateVariable[];

  // Source reference
  sourceFile: string;          // Where the hardcoded template lives
  sourceFunction: string;      // Function name in source file

  // State
  isCustomized: boolean;       // Has admin overridden the default?
  isActive: boolean;
  /**
   * Feature flag: when true, senders that support the new renderer will use
   * the editable Firestore template. When false (default) the legacy hardcoded
   * sender path runs unchanged. Lets admin A/B test per-template safely.
   */
  useCustomTemplate?: boolean;
  /** Optional fixed sub-header line for the email wrapper */
  headerSubtitle?: string;
  headerSubtitleEn?: string;
  lastEditedBy?: string;
  lastEditedAt?: any;
  createdAt?: any;
  updatedAt?: any;
}

// ============================================================
// EMAIL DESIGN SETTINGS — shared look & feel for all emails
// ============================================================

export interface EmailDesignSettings {
  // Header
  logoUrl: string;
  /** URL the logo links to (typically the website root) */
  logoLinkUrl: string;
  /** Logo height in px — width auto-scales to preserve aspect ratio */
  logoHeight: number;
  /** Horizontal alignment of header content (logo + title) */
  logoAlign: 'left' | 'center';
  headerBackground: string;     // e.g. "#2E2D2C"
  headerTextColor: string;      // e.g. "#ffffff"
  headerBorderColor: string;    // e.g. "#2E2D2C" (bottom border)
  /** Show or hide the email title (subject) under the logo */
  showHeaderTitle: boolean;
  showLogo: boolean;

  // Colors
  primaryColor: string;         // Buttons, badges, links — e.g. "#0EB0A6"
  successColor: string;         // Approve/tracking — e.g. "#22c55e"
  dangerColor: string;          // Reject/decline — e.g. "#ef4444"

  // Footer
  footerBackground: string;     // e.g. "#f8f9fa"
  footerTextColor: string;      // e.g. "#5f6368"
  companyName: string;
  companyTagline: string;
  companyTaglineEn: string;
  autoGeneratedNote: string;
  autoGeneratedNoteEn: string;

  // Contact
  contactEmail: string;
  contactPhone: string;

  // Address (for postal instructions)
  postalAddress: string;

  // General
  bodyMaxWidth: number;         // px — e.g. 600
  borderRadius: number;         // px — e.g. 12
  fontFamily: string;
}

export const DEFAULT_DESIGN_SETTINGS: EmailDesignSettings = {
  // Same logo as the website nav bar (logo-new.svg) — exported as PNG so it
  // renders correctly in Outlook desktop and Gmail-app which strip SVG.
  logoUrl: 'https://doxvl.se/logo-new.png',
  logoLinkUrl: 'https://doxvl.se',
  logoHeight: 53, // matches the 3.3rem max-height used in the website Header
  logoAlign: 'center',
  // Same background as the website header: rgba(46,45,44,1) = #2E2D2C
  headerBackground: '#2E2D2C',
  headerTextColor: '#ffffff',
  headerBorderColor: '#2E2D2C',
  showHeaderTitle: true,
  showLogo: true,

  primaryColor: '#0EB0A6',
  successColor: '#22c55e',
  dangerColor: '#ef4444',

  footerBackground: '#f8f9fa',
  footerTextColor: '#5f6368',
  companyName: 'DOX Visumpartner AB',
  companyTagline: 'Professionella visum- & legaliseringstjänster',
  companyTaglineEn: 'Professional visa & document legalisation services',
  autoGeneratedNote: 'Detta är ett automatiskt genererat meddelande.',
  autoGeneratedNoteEn: 'This is an automatically generated message.',

  contactEmail: 'info@doxvl.se',
  contactPhone: '08-40941900',

  postalAddress: 'DOX Visumpartner AB\nLivdjursgatan 4, våning 6\n121 62 Johanneshov',

  bodyMaxWidth: 600,
  borderRadius: 12,
  fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
};

const SETTINGS_DOC_ID = '__design_settings__';

export async function getEmailDesignSettings(): Promise<EmailDesignSettings> {
  try {
    const snap = await getDoc(doc(db, COLLECTION, SETTINGS_DOC_ID));
    if (snap.exists()) {
      return { ...DEFAULT_DESIGN_SETTINGS, ...snap.data() } as EmailDesignSettings;
    }
  } catch {
    // Fall back to defaults
  }
  return DEFAULT_DESIGN_SETTINGS;
}

export async function saveEmailDesignSettings(settings: EmailDesignSettings): Promise<void> {
  await setDoc(doc(db, COLLECTION, SETTINGS_DOC_ID), {
    ...settings,
    updatedAt: serverTimestamp(),
  });
}

// ============================================================
// SHARED EMAIL WRAPPER — generates consistent HTML for all emails
// ============================================================

export function generateEmailWrapper(options: {
  settings: EmailDesignSettings;
  lang: 'sv' | 'en';
  title: string;
  headerTitle: string;
  headerSubtitle?: string;
  bodyContent: string;
  showTrackingButton?: boolean;
  orderNumber?: string;
  showContactSection?: boolean;
}): string {
  const { settings: s, lang, title, headerTitle, headerSubtitle, bodyContent } = options;
  const isEn = lang === 'en';
  const showContact = options.showContactSection !== false;
  const showTracking = options.showTrackingButton && options.orderNumber;

  // Logo: clean, no border/padding/background. Wrapped in a link to the company site.
  // Height fixed via inline style; width auto-scales. Inserted as block to allow centering.
  const logoImg = s.showLogo ? `<img src="${s.logoUrl}" alt="${s.companyName}" height="${s.logoHeight}" style="height:${s.logoHeight}px;width:auto;border:0;outline:none;text-decoration:none;display:block;">` : '';
  const logoHtml = s.showLogo
    ? `<a href="${s.logoLinkUrl}" target="_blank" style="display:inline-block;text-decoration:none;border:0;outline:none;">${logoImg}</a>`
    : '';

  const trackingHtml = showTracking ? `
    <div style="background:#f0fdf4; border:2px solid ${s.successColor}; border-radius:8px; padding:20px; margin:22px 0; text-align:center;">
      <h3 style="color:#166534; margin:0 0 10px; font-size:17px;">${isEn ? 'Track Your Order' : 'Följ din order'}</h3>
      <p style="color:#15803d; margin:0 0 14px; font-size:14px;">${isEn ? 'Follow the progress of your application in real-time:' : 'Följ ditt ärende i realtid:'}</p>
      <a href="https://doxvl.se/orderstatus?order=${options.orderNumber}" style="display:inline-block; background:${s.successColor}; color:#fff; padding:12px 28px; border-radius:6px; text-decoration:none; font-weight:700; font-size:15px;">${isEn ? 'Track Order Status' : 'Se orderstatus'}</a>
    </div>
  ` : '';

  const contactHtml = showContact ? `
    <div style="background:#f0f9ff; border:1px solid #bae6fd; border-radius:8px; padding:18px; margin:22px 0; text-align:center;">
      <h3 style="margin:0 0 8px;">${isEn ? 'Questions?' : 'Har du frågor?'}</h3>
      <p style="margin:0;">${isEn ? 'Feel free to contact us:' : 'Kontakta oss gärna:'}</p>
      <p style="margin:8px 0 0;">📧 <a href="mailto:${s.contactEmail}" style="color:${s.primaryColor}">${s.contactEmail}</a> &nbsp; 📞 ${s.contactPhone}</p>
    </div>
  ` : '';

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
</head>
<body style="font-family:${s.fontFamily}; line-height:1.6; color:#202124; max-width:${s.bodyMaxWidth}px; margin:0 auto; background-color:#f8f9fa; padding:20px;">
  <div style="background-color:#ffffff; border-radius:${s.borderRadius}px; box-shadow:0 2px 6px rgba(0,0,0,0.08); overflow:hidden;">
    <div style="background:${s.headerBackground}; color:${s.headerTextColor}; padding:32px 36px 24px; text-align:${s.logoAlign}; border-bottom:2px solid ${s.headerBorderColor};">
      ${logoHtml}
      ${s.showHeaderTitle ? `<h1 style="margin:${s.showLogo ? '20px' : '0'} 0 0; font-size:22px; font-weight:700; letter-spacing:0.2px; color:${s.headerTextColor};">${headerTitle}</h1>` : ''}
      ${headerSubtitle && s.showHeaderTitle ? `<p style="color:${s.headerTextColor}; opacity:0.8; margin:8px 0 0;">${headerSubtitle}</p>` : ''}
    </div>
    <div style="padding:32px 36px;">
      ${bodyContent}
      ${trackingHtml}
      ${contactHtml}
    </div>
    <div style="background:${s.footerBackground}; padding:24px 36px; text-align:center; border-top:1px solid #eaecef;">
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;"><strong>${s.companyName}</strong></p>
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;">${isEn ? s.companyTaglineEn : s.companyTagline}</p>
      <p style="margin:5px 0; color:${s.footerTextColor}; font-size:13px;">${isEn ? s.autoGeneratedNoteEn : s.autoGeneratedNote}</p>
    </div>
  </div>
</body>
</html>`.trim();
}

// ============================================================
// COLLECTION REF
// ============================================================

const COLLECTION = 'emailTemplates';
const collectionRef = () => collection(db, COLLECTION);
const docRef = (id: string) => doc(db, COLLECTION, id);

// ============================================================
// CRUD
// ============================================================

export async function getAllEmailTemplates(): Promise<EmailTemplate[]> {
  const snap = await getDocs(collectionRef());
  const templates = snap.docs.map(d => ({ id: d.id, ...d.data() } as EmailTemplate));
  return templates.sort((a, b) => (a.processStep || 0) - (b.processStep || 0));
}

export async function getEmailTemplate(id: string): Promise<EmailTemplate | null> {
  const snap = await getDoc(docRef(id));
  if (!snap.exists()) return null;
  return { id: snap.id, ...snap.data() } as EmailTemplate;
}

export async function saveEmailTemplate(template: EmailTemplate): Promise<void> {
  const { id, ...data } = template;
  await setDoc(docRef(id), {
    ...data,
    updatedAt: serverTimestamp(),
  }, { merge: true });
}

export async function updateEmailTemplateContent(
  id: string,
  updates: {
    subjectSv?: string;
    subjectEn?: string;
    bodySv?: string;
    bodyEn?: string;
    isCustomized?: boolean;
    lastEditedBy?: string;
    useCustomTemplate?: boolean;
    headerSubtitle?: string;
    headerSubtitleEn?: string;
  }
): Promise<void> {
  // Only mark as customized when content actually changes (not when toggling the
  // feature flag alone), but always bump updatedAt/lastEditedAt.
  const contentChanged =
    updates.subjectSv !== undefined ||
    updates.subjectEn !== undefined ||
    updates.bodySv !== undefined ||
    updates.bodyEn !== undefined;
  await updateDoc(docRef(id), {
    ...updates,
    ...(contentChanged ? { isCustomized: true } : {}),
    updatedAt: serverTimestamp(),
    lastEditedAt: serverTimestamp(),
  });
}

export async function deleteEmailTemplate(id: string): Promise<void> {
  await deleteDoc(docRef(id));
}

// ============================================================
// SEED — Default template catalog (all 20 customer-facing emails)
// ============================================================

export const DEFAULT_EMAIL_TEMPLATES: Omit<EmailTemplate, 'createdAt' | 'updatedAt'>[] = [
  // === ORDER CONFIRMATION ===
  {
    id: 'order-confirmation-legalization',
    name: 'Orderbekräftelse (Legalisering — originaldokument)',
    nameEn: 'Order Confirmation (Legalization — original documents)',
    description: 'Skickas automatiskt till kund som ska skicka in originaldokument via post.',
    descriptionEn: 'Sent automatically to customers who will send original documents by mail.',
    category: 'order-confirmation',
    trigger: 'automatic',
    triggerEvent: 'order.created.legalization.original',
    processStep: 1,
    processGroup: 'Beställning',
    subjectSv: 'Bekräftelse på din beställning #{{orderNumber}}',
    subjectEn: 'Order Confirmation #{{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Tack för din beställning! Vi har mottagit din order och börjar nu handlägga den. Här är en sammanfattning:

{{orderSummary}}

{{nextStepsBlock}}

Du kan följa din order när som helst via länken nedan. Vi återkommer med uppdateringar via mail när din order rör sig framåt.`,
    bodyEn: `Dear {{customerName}},

Thank you for your order! We have received your order and will now start processing it. Here is a summary:

{{orderSummary}}

{{nextStepsBlock}}

You can track your order at any time via the link below. We will keep you updated by email as your order progresses.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'orderSummary', description: 'Ordersammanfattning (HTML-tabell, byggs automatiskt)', example: '<table>...</table>', isHtml: true },
      { key: 'nextStepsBlock', description: '"Nästa steg"-block med adresser och instruktioner (HTML, byggs automatiskt)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/components/order/steps/Step10ReviewSubmit.tsx',
    sourceFunction: 'inline (original documents flow)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'order-confirmation-legalization-upload',
    name: 'Orderbekräftelse (Legalisering — uppladdade filer)',
    nameEn: 'Order Confirmation (Legalization — uploaded files)',
    description: 'Skickas automatiskt till kund som har laddat upp sina dokument digitalt.',
    descriptionEn: 'Sent automatically to customers who have uploaded their documents digitally.',
    category: 'order-confirmation',
    trigger: 'automatic',
    triggerEvent: 'order.created.legalization.upload',
    processStep: 1,
    processGroup: 'Beställning',
    subjectSv: 'Bekräftelse på din beställning #{{orderNumber}}',
    subjectEn: 'Order Confirmation #{{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Tack för din beställning! Vi har mottagit dina uppladdade filer och börjar nu handlägga din ansökan. Här är en sammanfattning:

{{orderSummary}}

{{deliveredConfirmationBlock}}

Du kan följa din order när som helst via länken nedan.`,
    bodyEn: `Dear {{customerName}},

Thank you for your order! We have received your uploaded files and will now start processing your application. Here is a summary:

{{orderSummary}}

{{deliveredConfirmationBlock}}

You can track your order at any time via the link below.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'orderSummary', description: 'Ordersammanfattning (HTML-tabell, byggs automatiskt)', example: '<table>...</table>', isHtml: true },
      { key: 'deliveredConfirmationBlock', description: '"Vi har dina dokument"-bekräftelseruta (HTML, byggs automatiskt)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/components/order/steps/Step10ReviewSubmit.tsx',
    sourceFunction: 'generateCustomerConfirmationEmail (upload flow)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'order-confirmation-visa',
    name: 'Orderbekräftelse (Visum)',
    nameEn: 'Order Confirmation (Visa)',
    description: 'Skickas automatiskt till kund efter godkänd betalning av visumorder.',
    descriptionEn: 'Sent automatically to customer after successful visa order payment.',
    category: 'order-confirmation',
    trigger: 'automatic',
    triggerEvent: 'order.created.visa',
    processStep: 1,
    processGroup: 'Beställning',
    subjectSv: 'Bekräftelse på din visumbeställning #{{orderNumber}}',
    subjectEn: 'Visa Order Confirmation #{{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Tack för din visumbeställning! Vi har mottagit din ansökan till {{destinationCountry}} och börjar nu handlägga den. Här är en sammanfattning:

{{orderSummary}}

Vi återkommer till dig med uppdateringar via mail. Du kan följa din order när som helst via länken nedan.`,
    bodyEn: `Dear {{customerName}},

Thank you for your visa order! We have received your application for {{destinationCountry}} and will now start processing it. Here is a summary:

{{orderSummary}}

We will keep you updated by email as your order progresses. You can track your order at any time via the link below.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Thailand' },
      { key: 'visaProduct', description: 'Visumprodukt', example: 'Turistvisum 60 dagar' },
      { key: 'travelers', description: 'Resenärer (kommaseparerad)', example: 'Erik Svensson, Anna Svensson' },
      { key: 'orderSummary', description: 'Ordersammanfattning (HTML-tabell, byggs automatiskt)', example: '<table>...</table>', isHtml: true },
    ],
    sourceFile: 'src/components/order/visa/VisaStep10Review.tsx',
    sourceFunction: 'generateVisaConfirmationEmail',
    isCustomized: false,
    isActive: true,
  },

  // === DOCUMENT HANDLING ===
  {
    id: 'document-instructions',
    name: 'Dokumentinstruktioner',
    nameEn: 'Document Instructions',
    description: 'Handläggare skickar lista med dokument kunden behöver skicka in. Delas upp i post/digitalt.',
    descriptionEn: 'Admin sends list of documents customer needs to submit. Split into postal/digital.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendDocumentInstructions',
    processStep: 2,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Dokument som behövs för din visumansökan – {{orderNumber}}',
    subjectEn: 'Documents needed for your visa application – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Tack för din beställning. För att handlägga din visumansökan till {{destination}} behöver vi följande dokument:

{{documentList}}

Digitala dokument kan skickas genom att svara på detta mail eller till info@doxvl.se.

Hör av dig om du har några frågor.`,
    bodyEn: `Dear {{customerName}},

Thank you for your order. To process your visa application to {{destination}}, we need the following documents:

{{documentList}}

Digital documents can be sent by replying to this email or to info@doxvl.se.

Let us know if you have any questions.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destination', description: 'Destinationsland', example: 'Indien' },
      { key: 'documentList', description: 'Grupperad dokumentlista (HTML, byggs automatiskt — original / digitalt / valfritt)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'sendDocumentInstructionsEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'missing-documents',
    name: 'Saknade dokument',
    nameEn: 'Missing Documents',
    description: 'Påminnelse till kund om dokument som fortfarande saknas på checklistan.',
    descriptionEn: 'Reminder to customer about documents still missing from the checklist.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendMissingDocuments',
    processStep: 3,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Dokument behövs för din visumansökan – {{orderNumber}}',
    subjectEn: 'Documents needed for your visa application – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Tack för din visumansökan till {{destination}}. För att kunna gå vidare med din ansökan behöver vi fortfarande följande dokument:

{{missingDocsBlock}}

Vänligen skicka dessa dokument till oss så snart som möjligt så att vi kan skicka in din ansökan utan fördröjning.

Du kan svara på detta mail eller skicka dokumenten till info@doxvl.se.`,
    bodyEn: `Dear {{customerName}},

Thank you for your visa application to {{destination}}. To proceed with your application, we still need the following document(s):

{{missingDocsBlock}}

Please send these documents to us as soon as possible so we can submit your application without delay.

You can reply to this email or send the documents to info@doxvl.se.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destination', description: 'Destinationsland', example: 'Indien' },
      { key: 'missingDocsBlock', description: 'Lista över saknade dokument (HTML, byggs automatiskt)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'sendMissingDocumentsEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'document-request',
    name: 'Kompletteringsbegäran',
    nameEn: 'Document Request',
    description: 'Handläggare begär kompletterande dokument med uppladdningslänk.',
    descriptionEn: 'Admin requests additional documents with upload link.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendDocumentRequest',
    processStep: 3,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Begäran om komplettering',
    subjectEn: 'Document request',
    bodySv: 'Vi behöver ytterligare dokument för att kunna handlägga din ansökan.',
    bodyEn: 'We need additional documents to process your application.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'customMessage', description: 'Handläggarens meddelande', example: 'Vi behöver en tydligare kopia...' },
      { key: 'uploadUrl', description: 'Uppladdningslänk', example: 'https://doxvl.se/upload/...' },
    ],
    sourceFile: 'src/pages/api/document-request/send.ts',
    sourceFunction: 'generateEmailHtml',
    isCustomized: false,
    isActive: true,
  },

  // === DOCUMENT FLOW STATUS (legalization processing) ===
  // Templates for the inline emails sent from /admin/orders/[id].tsx when
  // handlers progress through the legalization workflow. Currently these
  // mails are still built inline in the order page; once wired up they
  // will use these templates as the source of truth.
  {
    id: 'legalization-documents-received',
    name: 'Dokument mottagna (legalisering)',
    nameEn: 'Documents Received (Legalization)',
    description: 'Bekräftelse till kund att vi tagit emot dokumenten som de skickat in.',
    descriptionEn: 'Confirmation to customer that we have received the documents they sent.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.documentsReceived',
    processStep: 4,
    processGroup: 'Handläggning',
    subjectSv: 'Bekräftelse: Vi har mottagit dina dokument – {{orderNumber}}',
    subjectEn: 'Confirmation: We have received your documents – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Vi bekräftar att vi har mottagit dina dokument för order {{orderNumber}}. Vi börjar nu handlägga din beställning och kommer att skicka uppdateringar via mail.

{{receivedDocsBlock}}

Hör av dig om du har några frågor.`,
    bodyEn: `Dear {{customerName}},

We confirm that we have received your documents for order {{orderNumber}}. We are now starting to process your order and will send updates by email.

{{receivedDocsBlock}}

Let us know if you have any questions.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'receivedDocsBlock', description: 'Lista över mottagna dokument (HTML, byggs automatiskt)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'inline (line ~3247)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'legalization-submitted-to-authority',
    name: 'Inskickat till myndighet',
    nameEn: 'Submitted to Authority',
    description: 'Bekräftelse till kund att ärendet är inlämnat till UD/handelskammare/notarius/ambassad.',
    descriptionEn: 'Confirmation to customer that the case has been submitted to UD/chamber/notary/embassy.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.submittedToAuthority',
    processStep: 5,
    processGroup: 'Handläggning',
    subjectSv: 'Bekräftelse: Ärendet är inlämnat till {{authorityName}} – {{orderNumber}}',
    subjectEn: 'Confirmation: Submitted to {{authorityName}} – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Vi har lämnat in ditt ärende till {{authorityName}}. Förväntad klar: {{expectedDate}}.

Vi återkommer till dig så snart vi har uppdaterad information.`,
    bodyEn: `Dear {{customerName}},

We have submitted your case to {{authorityName}}. Expected completion: {{expectedDate}}.

We will get back to you as soon as we have updated information.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'authorityName', description: 'Myndighet (UD, ambassad, etc.)', example: 'Utrikesdepartementet' },
      { key: 'expectedDate', description: 'Förväntad klar-datum', example: '2026-04-15' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'inline (line ~3471)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'legalization-tracking-registered',
    name: 'Spårningsnummer registrerat',
    nameEn: 'Tracking Number Registered',
    description: 'Notis till kund när handläggare registrerar ett spårningsnummer på ordern.',
    descriptionEn: 'Notification when the handler registers a tracking number on the order.',
    category: 'shipping',
    trigger: 'manual',
    triggerEvent: 'admin.trackingRegistered',
    processStep: 6,
    processGroup: 'Leverans',
    subjectSv: 'Spårningsnummer registrerat – {{orderNumber}}',
    subjectEn: 'Tracking number registered – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Vi har registrerat ett spårningsnummer för din order {{orderNumber}}.

Spårningsnummer: {{trackingNumber}}
Spårningslänk: {{trackingUrl}}

Du kan följa försändelsen via länken ovan.`,
    bodyEn: `Dear {{customerName}},

We have registered a tracking number for your order {{orderNumber}}.

Tracking number: {{trackingNumber}}
Tracking link: {{trackingUrl}}

You can follow the shipment via the link above.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'trackingNumber', description: 'Spårningsnummer', example: 'JJD000390001234' },
      { key: 'trackingUrl', description: 'Spårningslänk', example: 'https://tracking.dhl.com/...' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'inline (line ~3721)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'legalization-ready-for-pickup',
    name: 'Klar för upphämtning',
    nameEn: 'Ready for Pickup',
    description: 'Notis till kund att de färdiga dokumenten är klara för upphämtning på kontoret.',
    descriptionEn: 'Notification to customer that finished documents are ready for office pickup.',
    category: 'shipping',
    trigger: 'manual',
    triggerEvent: 'admin.readyForPickup',
    processStep: 7,
    processGroup: 'Leverans',
    subjectSv: 'Dina dokument är klara för upphämtning – {{orderNumber}}',
    subjectEn: 'Your documents are ready for pickup – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Dina färdiga dokument för order {{orderNumber}} är nu klara för upphämtning på vårt kontor.

Adress:
DOX Visumpartner AB
Livdjursgatan 4, våning 6
121 62 Johanneshov

Öppettider: må–fre 09:00–17:00

Vänligen ta med ID-handling vid upphämtning.`,
    bodyEn: `Dear {{customerName}},

Your finished documents for order {{orderNumber}} are now ready for pickup at our office.

Address:
DOX Visumpartner AB
Livdjursgatan 4, floor 6
121 62 Johanneshov

Opening hours: Mon–Fri 09:00–17:00

Please bring ID when picking up.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'inline (line ~4010)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'legalization-documents-shipped',
    name: 'Dokument skickade',
    nameEn: 'Documents Shipped',
    description: 'Notis till kund att de färdiga dokumenten har skickats med spårningsinformation.',
    descriptionEn: 'Notification to customer that finished documents have been shipped with tracking info.',
    category: 'shipping',
    trigger: 'manual',
    triggerEvent: 'admin.documentsShipped',
    processStep: 8,
    processGroup: 'Leverans',
    subjectSv: 'Dina dokument har skickats – {{orderNumber}}',
    subjectEn: 'Your documents have been shipped – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

Dina färdiga dokument för order {{orderNumber}} har nu skickats.

Fraktmetod: {{shippingMethod}}
Spårningsnummer: {{trackingNumber}}
Spårningslänk: {{trackingUrl}}

Försändelsen är på väg till dig och du kan följa den via länken ovan.`,
    bodyEn: `Dear {{customerName}},

Your finished documents for order {{orderNumber}} have now been shipped.

Shipping method: {{shippingMethod}}
Tracking number: {{trackingNumber}}
Tracking link: {{trackingUrl}}

The shipment is on its way to you and you can follow it via the link above.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'shippingMethod', description: 'Fraktmetod', example: 'PostNord REK' },
      { key: 'trackingNumber', description: 'Spårningsnummer', example: 'JJD000390001234' },
      { key: 'trackingUrl', description: 'Spårningslänk', example: 'https://tracking.dhl.com/...' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'inline (line ~4290)',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'legalization-document-request-form',
    name: 'Dokumentbegäran med uppladdningslänk',
    nameEn: 'Document Request (with upload link)',
    description: 'Begär kompletterande dokument med en säker uppladdningslänk till kunden.',
    descriptionEn: 'Request additional documents with a secure upload link sent to the customer.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendDocumentRequestForm',
    processStep: 3,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Vi behöver kompletterande dokument – {{orderNumber}}',
    subjectEn: 'Additional documents needed – {{orderNumber}}',
    bodySv: `Hej {{customerName}}!

För att kunna fortsätta handlägga din order {{orderNumber}} behöver vi ytterligare dokument.

{{customMessage}}

Vänligen ladda upp dokumenten via länken nedan: {{uploadUrl}}

Hör av dig om du har frågor.`,
    bodyEn: `Dear {{customerName}},

To continue processing your order {{orderNumber}}, we need additional documents.

{{customMessage}}

Please upload the documents via the link below: {{uploadUrl}}

Let us know if you have any questions.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'customMessage', description: 'Handläggarens meddelande', example: 'Vi behöver en tydligare kopia av sidan 2.' },
      { key: 'uploadUrl', description: 'Säker uppladdningslänk', example: 'https://doxvl.se/upload/abc123' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'sendDocumentRequest',
    isCustomized: false,
    isActive: true,
  },

  // === VISA STATUS UPDATES ===
  {
    id: 'visa-docs-received',
    name: 'Dokument mottagna',
    nameEn: 'Documents Received',
    description: 'Bekräftelse till kund att vi tagit emot deras dokument.',
    descriptionEn: 'Confirmation to customer that we received their documents.',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.docsReceived',
    processStep: 4,
    processGroup: 'Handläggning',
    subjectSv: 'Vi har mottagit dina dokument',
    subjectEn: 'We have received your documents',
    bodySv: 'Vi bekräftar att vi mottagit dina dokument. Vårt team granskar nu din ansökan.',
    bodyEn: 'We confirm that we have received your documents. Our team is now reviewing your application.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Thailand' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaDocsReceivedEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'visa-submitted-portal',
    name: 'Ansökan inskickad (portal)',
    nameEn: 'Application Submitted (Portal)',
    description: 'Bekräftelse att visumansökan skickats in via portalen.',
    descriptionEn: 'Confirmation that visa application was submitted via portal.',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.submittedPortal',
    processStep: 5,
    processGroup: 'Handläggning',
    subjectSv: 'Din visumansökan har skickats in',
    subjectEn: 'Your visa application has been submitted',
    bodySv: 'Vi har nu skickat in din visumansökan. Du kommer att få besked så snart vi har ett svar.',
    bodyEn: 'We have now submitted your visa application. You will be notified as soon as we have a response.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Indien' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaSubmittedEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'visa-embassy-submitted',
    name: 'Inskickad till ambassad',
    nameEn: 'Submitted to Embassy',
    description: 'Bekräftelse att passet lämnats in till ambassaden (sticker-visum).',
    descriptionEn: 'Confirmation that passport was submitted to embassy (sticker visa).',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.embassySubmitted',
    processStep: 6,
    processGroup: 'Handläggning',
    subjectSv: 'Ditt pass har lämnats in till ambassaden',
    subjectEn: 'Your passport has been submitted to the embassy',
    bodySv: 'Vi har lämnat in ditt pass och din ansökan till ambassaden.',
    bodyEn: 'We have submitted your passport and application to the embassy.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Kina' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaEmbassySubmittedEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'visa-approved',
    name: 'Visum godkänt',
    nameEn: 'Visa Approved',
    description: 'Goda nyheter — visumet har beviljats!',
    descriptionEn: 'Great news — the visa has been approved!',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.approved',
    processStep: 7,
    processGroup: 'Resultat',
    subjectSv: 'Goda nyheter! Ditt visum har godkänts',
    subjectEn: 'Great news! Your visa has been approved',
    bodySv: 'Vi har goda nyheter — ditt visum har godkänts!',
    bodyEn: 'We have great news — your visa has been approved!',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'USA' },
      { key: 'visaProduct', description: 'Visumprodukt', example: 'B1/B2 Turistvisum' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaApprovedEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'visa-rejected',
    name: 'Visum avslaget',
    nameEn: 'Visa Rejected',
    description: 'Meddelande att visumansökan har avslagits.',
    descriptionEn: 'Notification that visa application was denied.',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.rejected',
    processStep: 7,
    processGroup: 'Resultat',
    subjectSv: 'Uppdatering om visumansökan',
    subjectEn: 'Visa application update',
    bodySv: 'Vi beklagar att meddela att din visumansökan tyvärr har avslagits.',
    bodyEn: 'We regret to inform you that your visa application has been denied.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Australien' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaRejectedEmail',
    isCustomized: false,
    isActive: true,
  },

  // === DELIVERY ===
  {
    id: 'evisa-delivery',
    name: 'E-visum levererat',
    nameEn: 'E-Visa Delivered',
    description: 'E-visumet skickas som bilaga till kund.',
    descriptionEn: 'E-visa sent as attachment to customer.',
    category: 'visa-status',
    trigger: 'manual',
    triggerEvent: 'visa.evisaDelivered',
    processStep: 8,
    processGroup: 'Leverans',
    subjectSv: 'Ditt e-visum är klart!',
    subjectEn: 'Your e-visa is ready!',
    bodySv: 'Ditt e-visum är nu klart och bifogas i detta mail.',
    bodyEn: 'Your e-visa is now ready and attached to this email.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'destinationCountry', description: 'Destinationsland', example: 'Indien' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateEVisaDeliveryEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'visa-return-shipping',
    name: 'Pass skickat (retur)',
    nameEn: 'Passport Shipped (Return)',
    description: 'Kundens pass har skickats tillbaka med spårningsnummer.',
    descriptionEn: 'Customer passport shipped back with tracking number.',
    category: 'shipping',
    trigger: 'manual',
    triggerEvent: 'visa.returnShipping',
    processStep: 8,
    processGroup: 'Leverans',
    subjectSv: 'Ditt pass har skickats',
    subjectEn: 'Your passport has been shipped',
    bodySv: 'Vi har skickat ditt pass. Här är din spårningsinformation.',
    bodyEn: 'We have shipped your passport. Here is your tracking information.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'trackingNumber', description: 'Spårningsnummer', example: 'JJD000390001234' },
      { key: 'trackingUrl', description: 'Spårningslänk', example: 'https://tracking.dhl.com/...' },
    ],
    sourceFile: 'src/components/order/templates/visaStatusUpdateEmail.ts',
    sourceFunction: 'generateVisaReturnShippingEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'dhl-pickup-label',
    name: 'DHL upphämtningsetikett',
    nameEn: 'DHL Pickup Label',
    description: 'Skickar DHL-etikett och upphämtningsinstruktioner till kund.',
    descriptionEn: 'Sends DHL label and pickup instructions to customer.',
    category: 'shipping',
    trigger: 'manual',
    triggerEvent: 'admin.sendPickupLabel',
    processStep: 2,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Upphämtningsinstruktioner',
    subjectEn: 'Pickup Instructions',
    bodySv: 'Här är din DHL-etikett och instruktioner för upphämtning.',
    bodyEn: 'Here is your DHL label and pickup instructions.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'trackingNumber', description: 'DHL spårningsnummer', example: 'JJD000390001234' },
      { key: 'pickupDate', description: 'Upphämtningsdatum', example: '2026-04-15' },
      { key: 'pickupAddress', description: 'Upphämtningsadress', example: 'Storgatan 1, Stockholm' },
    ],
    sourceFile: 'src/pages/api/dhl/send-pickup-label.ts',
    sourceFunction: 'generatePickupEmailHtml',
    isCustomized: false,
    isActive: true,
  },

  // === ADDRESS & PRICE CONFIRMATIONS ===
  {
    id: 'address-confirmation',
    name: 'Adressbekräftelse',
    nameEn: 'Address Confirmation',
    description: 'Bekräfta/ändra hämtnings- eller returadress.',
    descriptionEn: 'Confirm/edit pickup or return address.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendAddressConfirmation',
    processStep: 2,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Bekräfta din {{addressType}} — Order #{{orderNumber}}',
    subjectEn: 'Confirm your {{addressType}} — Order #{{orderNumber}}',
    bodySv: `<p>Hej {{customerName}}!</p>
<p>Vi behöver din bekräftelse av <strong>{{addressType}}</strong> innan vi kan fortsätta med din order.</p>
<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:20px;margin:20px 0;">
  <h3 style="margin:0 0 12px 0;color:#202124;font-size:16px;">📍 Adress</h3>
  <p style="margin:0;color:#202124;line-height:1.6;">{{address}}</p>
</div>
<div style="background:#fef3c7;border:1px solid #f59e0b;border-radius:8px;padding:14px;margin:16px 0;">
  <p style="margin:0;color:#92400e;font-size:14px;">⚠️ Kontrollera att adressen är korrekt. Felaktig adress kan leda till förseningar eller missade leveranser.</p>
</div>
<div style="text-align:center;margin:24px 0;">
  <a href="{{confirmationUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:14px 32px;border-radius:6px;text-decoration:none;font-weight:bold;font-size:15px;">✓ Bekräfta eller ändra adress</a>
</div>`,
    bodyEn: `<p>Dear {{customerName}},</p>
<p>We need you to confirm your <strong>{{addressType}}</strong> before we can proceed with your order.</p>
<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:20px;margin:20px 0;">
  <h3 style="margin:0 0 12px 0;color:#202124;font-size:16px;">📍 Address</h3>
  <p style="margin:0;color:#202124;line-height:1.6;">{{address}}</p>
</div>
<div style="background:#fef3c7;border:1px solid #f59e0b;border-radius:8px;padding:14px;margin:16px 0;">
  <p style="margin:0;color:#92400e;font-size:14px;">⚠️ Please verify the address is correct. An incorrect address may cause delays or missed deliveries.</p>
</div>
<div style="text-align:center;margin:24px 0;">
  <a href="{{confirmationUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:14px 32px;border-radius:6px;text-decoration:none;font-weight:bold;font-size:15px;">✓ Confirm or edit address</a>
</div>`,
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'address', description: 'Fullständig adress (HTML, en rad per fält)', example: 'Storgatan 1<br>111 23 Stockholm', isHtml: true },
      { key: 'addressType', description: 'Typ (upphämtningsadress/returadress)', example: 'upphämtningsadress' },
      { key: 'confirmationUrl', description: 'Länk till bekräftelsesidan', example: 'https://doxvl.se/confirm-address/abc123' },
    ],
    sourceFile: 'src/pages/api/address-confirmation/send.ts',
    sourceFunction: 'handler',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'embassy-price-confirmation',
    name: 'Ambassadavgift-bekräftelse',
    nameEn: 'Embassy Fee Confirmation',
    description: 'Bekräfta ny ambassadavgift med kund (vid prisändring).',
    descriptionEn: 'Confirm new embassy fee with customer (on price change).',
    category: 'billing',
    trigger: 'manual',
    triggerEvent: 'admin.sendEmbassyPriceConfirmation',
    processStep: 3,
    processGroup: 'Dokumenthantering',
    subjectSv: 'Bekräfta ambassadavgift',
    subjectEn: 'Confirm embassy fee',
    bodySv: 'Vi behöver din bekräftelse av den officiella ambassadavgiften.',
    bodyEn: 'We need your confirmation of the official embassy fee.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'originalPrice', description: 'Ursprungligt pris', example: '1500 kr' },
      { key: 'newPrice', description: 'Nytt pris', example: '1800 kr' },
    ],
    sourceFile: 'src/pages/api/embassy-price-confirmation/send.ts',
    sourceFunction: 'handler',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'quote',
    name: 'Offert',
    nameEn: 'Price Quote',
    description: 'Skicka prisförslag med godkänn/avböj-knappar.',
    descriptionEn: 'Send price quote with accept/decline buttons.',
    category: 'billing',
    trigger: 'manual',
    triggerEvent: 'admin.sendQuote',
    processStep: 1,
    processGroup: 'Beställning',
    subjectSv: 'Offert',
    subjectEn: 'Price Quote',
    bodySv: 'Här är vår offert baserad på dina önskemål.',
    bodyEn: 'Here is our quote based on your requirements.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'lineItems', description: 'Prisrader (HTML-tabell)', example: '<table>...</table>' },
      { key: 'totalAmount', description: 'Totalbelopp', example: '2500 kr' },
      { key: 'quoteUrl', description: 'Länk till offert', example: 'https://doxvl.se/quote/...' },
    ],
    sourceFile: 'src/pages/api/quote/send.ts',
    sourceFunction: 'generateQuoteEmailHtml',
    isCustomized: false,
    isActive: true,
  },

  // === FILES & PASSWORDS ===
  {
    id: 'send-files',
    name: 'Skicka filer till kund',
    nameEn: 'Send Files to Customer',
    description: 'Handläggare skickar färdiga dokument (e-visum, certifikat etc.) till kund.',
    descriptionEn: 'Admin sends completed documents (e-visa, certificates etc.) to customer.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendFiles',
    processStep: 8,
    processGroup: 'Leverans',
    subjectSv: 'Dokument för din order',
    subjectEn: 'Documents for your order',
    bodySv: 'Här är dokumenten för din beställning.',
    bodyEn: 'Here are the documents for your order.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'fileList', description: 'Lista med filer (HTML)', example: '<ul><li>e-visa.pdf</li></ul>' },
      { key: 'customMessage', description: 'Meddelande från handläggare', example: 'Bifogat finner du...' },
    ],
    sourceFile: 'src/pages/api/admin/send-files-to-customer.ts',
    sourceFunction: 'generateFilesEmail',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'send-password',
    name: 'Lösenord för dokument',
    nameEn: 'Document Password',
    description: 'Skickar filens lösenord separat för säkerhet.',
    descriptionEn: 'Sends file password separately for security.',
    category: 'document-handling',
    trigger: 'manual',
    triggerEvent: 'admin.sendPassword',
    processStep: 8,
    processGroup: 'Leverans',
    subjectSv: 'Lösenord för ditt dokument',
    subjectEn: 'Password for your document',
    bodySv: 'Här är lösenordet för att öppna ditt dokument.',
    bodyEn: 'Here is the password to open your document.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'password', description: 'Lösenord', example: 'ABC123' },
    ],
    sourceFile: 'src/pages/api/admin/send-password-email.ts',
    sourceFunction: 'generatePasswordEmail',
    isCustomized: false,
    isActive: true,
  },

  // === CUSTOM / OTHER ===
  {
    id: 'custom-email',
    name: 'Anpassat mail',
    nameEn: 'Custom Email',
    description: 'Fritext-mail som handläggare skriver och skickar till kund. {{message}} är handläggarens text.',
    descriptionEn: 'Free-text email written and sent by admin to customer. {{message}} is the handler text.',
    category: 'custom',
    trigger: 'manual',
    triggerEvent: 'admin.sendCustomEmail',
    processStep: 0,
    processGroup: 'Övriga',
    subjectSv: '{{subject}}',
    subjectEn: '{{subject}}',
    bodySv: `<p>Hej {{customerName}}!</p>
<p style="color:#6b7280;font-size:14px;">Angående din order #{{orderNumber}}:</p>
<div style="background:#f9fafb;border-left:4px solid #0EB0A6;padding:16px;margin:16px 0;">
  <p style="color:#374151;margin:0;white-space:pre-wrap;line-height:1.6;">{{message}}</p>
</div>`,
    bodyEn: `<p>Dear {{customerName}},</p>
<p style="color:#6b7280;font-size:14px;">Regarding your order #{{orderNumber}}:</p>
<div style="background:#f9fafb;border-left:4px solid #0EB0A6;padding:16px;margin:16px 0;">
  <p style="color:#374151;margin:0;white-space:pre-wrap;line-height:1.6;">{{message}}</p>
</div>`,
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'subject', description: 'Ämnesrad (handläggaren anger)', example: 'Ang. din beställning' },
      { key: 'message', description: 'Meddelande (handläggaren skriver)', example: 'Hej Erik, vi behöver...' },
    ],
    sourceFile: 'src/pages/api/send-custom-email.ts',
    sourceFunction: 'generateEmailHtml',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'order-update-notification',
    name: 'Orderuppdatering',
    nameEn: 'Order Update Notification',
    description: 'Notis till kund när orderdetaljer ändras av handläggare.',
    descriptionEn: 'Notification when order details are changed by admin.',
    category: 'custom',
    trigger: 'manual',
    triggerEvent: 'admin.sendOrderUpdate',
    processStep: 0,
    processGroup: 'Övriga',
    subjectSv: 'Order uppdaterad',
    subjectEn: 'Order Updated',
    bodySv: 'Följande ändringar har gjorts i din beställning.',
    bodyEn: 'The following changes have been made to your order.',
    variables: [
      { key: 'customerName', description: 'Kundens namn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'changes', description: 'Ändringstabell (HTML)', example: '<table>Fält → Nytt värde</table>' },
      { key: 'customMessage', description: 'Meddelande från handläggare', example: '' },
    ],
    sourceFile: 'src/pages/api/order-update-notification/send.ts',
    sourceFunction: 'handler',
    isCustomized: false,
    isActive: true,
  },
  {
    id: 'invoice',
    name: 'Faktura',
    nameEn: 'Invoice',
    description: 'Faktura skickas med bifogad PDF. Mailet skickas till fakturor@visumpartner.se för manuell hantering.',
    descriptionEn: 'Invoice sent with attached PDF. Email goes to fakturor@visumpartner.se for manual handling.',
    category: 'billing',
    trigger: 'manual',
    triggerEvent: 'admin.sendInvoice',
    processStep: 9,
    processGroup: 'Leverans',
    subjectSv: 'Faktura {{invoiceNumber}} från DOX Visumpartner AB',
    subjectEn: 'Invoice {{invoiceNumber}} from DOX Visumpartner AB',
    bodySv: `Hej {{customerName}}!

Tack för att du har valt DOX Visumpartner AB för dina legaliseringstjänster.

Här är information om din faktura:

Fakturanummer: {{invoiceNumber}}
Fakturadatum: {{invoiceDate}}
Förfallodatum: {{dueDate}}
Att betala: {{totalAmount}}
Betalningsreferens: {{paymentReference}}

Fakturan bifogas som PDF. Vänligen betala enligt betalningsvillkoren.

Vid frågor kontakta oss på info@doxvl.se eller 070-123 45 67.`,
    bodyEn: `Hello {{customerName}},

Thank you for choosing DOX Visumpartner AB for your legalization services.

Here is your invoice information:

Invoice number: {{invoiceNumber}}
Invoice date: {{invoiceDate}}
Due date: {{dueDate}}
Amount due: {{totalAmount}}
Payment reference: {{paymentReference}}

The invoice is attached as a PDF. Please pay according to the payment terms.

If you have any questions, please contact us at info@doxvl.se or 070-123 45 67.`,
    variables: [
      { key: 'customerName', description: 'Kundens förnamn', example: 'Erik' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'SWE000325' },
      { key: 'invoiceNumber', description: 'Fakturanummer', example: 'INV-2026-001' },
      { key: 'totalAmount', description: 'Totalbelopp', example: '2500 SEK' },
      { key: 'invoiceDate', description: 'Fakturadatum', example: '2026-04-09' },
      { key: 'dueDate', description: 'Förfallodatum', example: '2026-04-23' },
      { key: 'paymentReference', description: 'Betalningsreferens (OCR)', example: '1234567890' },
    ],
    sourceFile: 'src/services/invoiceService.ts',
    sourceFunction: 'sendInvoiceEmail',
    isCustomized: false,
    isActive: true,
  },

  // === INTERNAL — sent to handlers/managers, not customers ===
  {
    id: 'reminder-created-internal',
    name: 'Reminder skapad — notis till handläggare',
    nameEn: 'Reminder Created — handler notification',
    description: 'Internt mail som skickas när en reminder skapas med "Notify email" ifyllt. Går till handläggaren själv eller en utpekad mottagare.',
    descriptionEn: 'Internal email sent when a reminder is created with a "Notify email". Goes to the assignee or a designated recipient.',
    category: 'internal',
    trigger: 'manual',
    triggerEvent: 'reminder.created',
    processStep: 1,
    processGroup: 'Internal',
    subjectSv: '🔔 Reminder: {{message}} — Order #{{orderNumber}}',
    subjectEn: '🔔 Reminder: {{message}} — Order #{{orderNumber}}',
    bodySv: `<p>{{message}}</p>
<p style="color:#6b7280;font-size:14px;">Förfaller: <strong>{{dueDate}}</strong></p>
<hr style="border:none;border-top:1px solid #eee;margin:16px 0;">
<p style="font-size:14px;"><strong>Order:</strong> #{{orderNumber}}</p>
<p style="font-size:14px;"><strong>Tilldelad till:</strong> {{assigneeName}}</p>
<p style="font-size:14px;"><strong>Skapad av:</strong> {{createdByName}}</p>
<div style="text-align:center;margin:24px 0;">
  <a href="{{orderUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;">Öppna order</a>
</div>`,
    bodyEn: `<p>{{message}}</p>
<p style="color:#6b7280;font-size:14px;">Due: <strong>{{dueDate}}</strong></p>
<hr style="border:none;border-top:1px solid #eee;margin:16px 0;">
<p style="font-size:14px;"><strong>Order:</strong> #{{orderNumber}}</p>
<p style="font-size:14px;"><strong>Assigned to:</strong> {{assigneeName}}</p>
<p style="font-size:14px;"><strong>Created by:</strong> {{createdByName}}</p>
<div style="text-align:center;margin:24px 0;">
  <a href="{{orderUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;">Open Order</a>
</div>`,
    variables: [
      { key: 'message', description: 'Reminder-meddelandet', example: 'Follow up with embassy' },
      { key: 'dueDate', description: 'Förfallodatum (formaterat)', example: '2026-04-15 09:00' },
      { key: 'orderNumber', description: 'Ordernummer', example: 'VISA000451' },
      { key: 'assigneeName', description: 'Tilldelad handläggare', example: 'Alexander' },
      { key: 'createdByName', description: 'Användare som skapade remindern', example: 'Henrik' },
      { key: 'orderUrl', description: 'Direktlänk till ordern', example: 'https://doxvl.se/admin/orders/abc123' },
    ],
    sourceFile: 'src/pages/admin/orders/[id].tsx',
    sourceFunction: 'handleCreateReminder',
    isCustomized: false,
    isActive: true,
    useCustomTemplate: true, // brand-new mail — use the new renderer from day one
  },
  {
    id: 'reminder-ping-internal',
    name: 'Reminder ping — chef pingar handläggare',
    nameEn: 'Reminder Ping — manager nudges handler',
    description: 'Skickas från Manager-vyn när en chef pingar en handläggare om en pågående reminder.',
    descriptionEn: 'Sent from the Manager view when a manager nudges a handler about an open reminder.',
    category: 'internal',
    trigger: 'manual',
    triggerEvent: 'reminder.ping',
    processStep: 2,
    processGroup: 'Internal',
    subjectSv: '🔔 Påminnelse från {{managerName}}: {{message}}',
    subjectEn: '🔔 Reminder ping from {{managerName}}: {{message}}',
    bodySv: `<p>Hej {{assigneeName}},</p>
<p style="color:#6b7280;font-size:14px;"><strong>{{managerName}}</strong> följer upp den här remindern:</p>
<div style="background:#fef2f2;border-left:4px solid #dc2626;padding:12px 16px;margin:16px 0;">
  <p style="margin:0 0 8px 0;color:#991b1b;font-weight:bold;font-size:16px;">{{message}}</p>
  <p style="margin:0;color:#6b7280;font-size:13px;">Förfaller: <strong>{{dueDate}}</strong></p>
  <p style="margin:4px 0 0 0;color:#6b7280;font-size:13px;">{{entityLabel}}</p>
</div>
{{pingNoteBlock}}
<div style="text-align:center;margin:24px 0;">
  <a href="{{entityUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;">Öppna {{entityType}}</a>
</div>`,
    bodyEn: `<p>Hi {{assigneeName}},</p>
<p style="color:#6b7280;font-size:14px;"><strong>{{managerName}}</strong> is following up on this reminder:</p>
<div style="background:#fef2f2;border-left:4px solid #dc2626;padding:12px 16px;margin:16px 0;">
  <p style="margin:0 0 8px 0;color:#991b1b;font-weight:bold;font-size:16px;">{{message}}</p>
  <p style="margin:0;color:#6b7280;font-size:13px;">Due: <strong>{{dueDate}}</strong></p>
  <p style="margin:4px 0 0 0;color:#6b7280;font-size:13px;">{{entityLabel}}</p>
</div>
{{pingNoteBlock}}
<div style="text-align:center;margin:24px 0;">
  <a href="{{entityUrl}}" style="display:inline-block;background:#0EB0A6;color:white;padding:12px 28px;border-radius:6px;text-decoration:none;font-weight:bold;">Open {{entityType}}</a>
</div>`,
    variables: [
      { key: 'assigneeName', description: 'Handläggarens namn', example: 'Alexander' },
      { key: 'managerName', description: 'Chefens namn', example: 'Henrik' },
      { key: 'message', description: 'Reminder-meddelandet', example: 'Follow up with embassy' },
      { key: 'dueDate', description: 'Förfallodatum (formaterat)', example: '2026-04-15 09:00' },
      { key: 'entityLabel', description: 'Etikett för order/lead', example: 'Order #VISA000451' },
      { key: 'entityType', description: 'Typ (Order/Lead)', example: 'Order' },
      { key: 'entityUrl', description: 'Direktlänk', example: 'https://doxvl.se/admin/orders/abc123' },
      { key: 'pingNoteBlock', description: 'Manager-not (HTML, redan formaterad)', example: '<div>...</div>', isHtml: true },
    ],
    sourceFile: 'src/pages/admin/manager.tsx',
    sourceFunction: 'sendPing',
    isCustomized: false,
    isActive: true,
    useCustomTemplate: true, // brand-new mail — use the new renderer from day one
  },
];

/**
 * Seed all default templates into Firestore.
 * - Always creates missing templates.
 * - For existing templates: refreshes metadata (name, description, variables,
 *   sourceFile, processGroup, ...) and refreshes subject/body content only when
 *   the template has NOT been customized by admin (`isCustomized: false`),
 *   UNLESS `force: true` is passed — then customized content is overwritten too.
 *
 * The `useCustomTemplate` flag is always preserved (admin's choice is sticky).
 */
export async function seedEmailTemplates(
  options: { force?: boolean } = {}
): Promise<{ created: number; refreshed: number; preservedCustomized: number; forceOverwritten: number }> {
  let created = 0;
  let refreshed = 0;
  let preservedCustomized = 0;
  let forceOverwritten = 0;
  const force = options.force === true;

  for (const template of DEFAULT_EMAIL_TEMPLATES) {
    const existing = await getDoc(docRef(template.id));
    if (!existing.exists()) {
      await setDoc(docRef(template.id), {
        ...template,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
      created++;
      continue;
    }

    const existingData = existing.data() as Partial<EmailTemplate>;
    const isCustomized = existingData.isCustomized === true;

    // Always refresh metadata. Refresh content only when admin has not customized it,
    // unless force is set.
    const refreshPayload: Record<string, any> = {
      name: template.name,
      nameEn: template.nameEn,
      description: template.description,
      descriptionEn: template.descriptionEn,
      category: template.category,
      trigger: template.trigger,
      triggerEvent: template.triggerEvent,
      processStep: template.processStep,
      processGroup: template.processGroup,
      variables: template.variables,
      sourceFile: template.sourceFile,
      sourceFunction: template.sourceFunction,
      updatedAt: serverTimestamp(),
    };

    const shouldRefreshContent = !isCustomized || force;

    if (shouldRefreshContent) {
      refreshPayload.subjectSv = template.subjectSv;
      refreshPayload.subjectEn = template.subjectEn;
      refreshPayload.bodySv = template.bodySv;
      refreshPayload.bodyEn = template.bodyEn;
      if (force && isCustomized) {
        // Reset the customized flag now that content is back to defaults
        refreshPayload.isCustomized = false;
        forceOverwritten++;
      }
      // Only set the default useCustomTemplate flag for templates that ship with one
      // (i.e. internal reminder templates) — preserve admin's existing choice otherwise
      if (template.useCustomTemplate !== undefined && existingData.useCustomTemplate === undefined) {
        refreshPayload.useCustomTemplate = template.useCustomTemplate;
      }
    } else {
      preservedCustomized++;
    }

    await updateDoc(docRef(template.id), refreshPayload);
    refreshed++;
  }

  return { created, refreshed, preservedCustomized, forceOverwritten };
}
